### ISSUE TITLE
[🏠 Internal]: v8 issue list

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8541]
As we a making progress on v8 we put some issues on the back burner to visit later:

- performance e2e test was skipped due to issues: https://github.com/webdriverio/webdriverio/blob/587a93b6d941f70e00cb99732d9e1b9d518ad3b4/e2e/wdio/headless/test.e2e.ts#L19
- Windows smoke tests were failing due to https://github.com/mochajs/mocha/pull/4901
- Windows e2e tests were disabled due to similar issues
  ```
  Spec file(s): file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/test.e2e.ts
  Error: Error: Cannot find module 'D:\D:\a\webdriverio\webdriverio\e2e\wdio\headless\test.e2e.ts' imported from 
  D:\a\webdriverio\webdriverio\packages\wdio-mocha-framework\node_modules\mocha\lib\nodejs\esm-utils.js
  ```
- also it seems on Windows it has issues finding Chrome browser in CI
  ```
  FAIL  e2e/element.test.ts [ e2e/element.test.ts ]
  Error: No Chrome installations found.
    ❯ new LauncherError packages/devtools/node_modules/chrome-launcher/src/utils.ts:31:18
   ```
- unskip unit tests and bump test coverage

**Comment by christian-bromann** [comment]
Bumped unit tests to a degree that we can be satisfied with coverage (>90%).

Created a separate issue to look into the Windows story - see #8689 - as well as performance testing issue #8690
