### ISSUE TITLE
[🐛 Bug]: Regression with Jasmine types

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#11999]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.18.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  injectGlobals: false
}
```

### What happened?

I'm using **WDIO Testrunner** with **TypeScript** and **Jasmine** integration.

### Before
I was used to import everything from wdio globals so that the default global expect would come from Jasmine.
#### tsconfig.json
```json
{
  "types": [
    "node",
    "expect-webdriverio/jasmine",
    "@wdio/jasmine-framework"
  ]
}
```
#### test.e2e.ts
```ts
import { browser, $, expect as expectWdio } from '@wdio/globals';

const messageEl = $('.message');

// 1. Here, "expectWdio" comes from wdio because I'm explicitly importing it
await expectWdio(messageEl).toHaveText('TEST', { message: 'Message should be equal to TEST' });

// 2. Here, "expectAsync" comes from Jasmine (thanks to tsconfig types)
await expectAsync(messageEl.getText()).withContext('Message should be equal to TEST').toBeResolvedTo('TEST');

// 3. Here, "expect" comes from Jasmine (thanks to tsconfig types)
expect(await messageEl.getText()).withContext('Message should be equal to TEST').toBe('TEST');
```

### Now
It seems that wdio's "expect" is now globally imported via @wdio/globals.
So importing @wdio/globals in a test file will ALWAYS override Jasmine's expect.

Resulting, in my case, with 3. no more working (as expect is now coming from wdio):
<img width="1267" alt="Screen Shot 2024-01-12 at 20 57 29" src="https://github.com/webdriverio/webdriverio/assets/674862/a6c9c511-6cf4-42c4-b970-d58faefa90db">

I know I can do better here, as stated in the best practices guide, where we should use built-in assertions instead.
But I do miss sometimes the use of Jasmine.withContext which is really useful, especially during failure.
#### For example:
```ts
const options = await selectEl.getOptions();
expect(options.length).withContext('Select should have 3 options').toBe(3);
```

I'm also noticing another suspicious behavior when using wdio's expect with primitives, where the expected type is "unknown" instead of inheriting from the actual type:
<img width="643" alt="Screen Shot 2024-01-12 at 20 54 43" src="https://github.com/webdriverio/webdriverio/assets/674862/39565a42-da28-45b7-ad28-552ae7e0ff37">

### What is your expected behavior?

I'm expecting both wdio and jasmine expect to work together.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

This seems related to #11533.

**Comment by Badisi** [comment]
Took me a while but I finally found the [commit](https://github.com/webdriverio/expect-webdriverio/commit/359155cd47f99a0c914f60354e956f82d63548f6#diff-38e3b0b46c9d69ee540371ca42b1e1492e271fa48ebffcc11f6885de396bcdf5R3) that introduced the regression by adding this line:

```ts
/* expect-webdriverio/types/jest-global.d.ts */
declare const expect: ExpectWebdriverIO.Expect
```

----

What happen is this:
1. You import wdio globals from a test file
   ```ts
   import { ... } from '@wdio/globals';
   ```
2. @wdio/globals reference a types file
   ```ts
    /// <reference path="../types.d.ts" />
    ```
3. The types file import expect-webdriverio
     ```ts
    type ExpectType = import('expect-webdriverio').Expect;
    ```
4. expect-webdriverio exports jest-global by default via its package.json
    ```json
    "exports": {
       ".": [
        {
          "types": "./types/jest-global.d.ts",
          "import": "./lib/index.js"
        },
        "./lib/index.js"
      ]
    }
    ```
5. jest-global.d.ts now has an **expect** const
6. So this expect overrides the one from Jasmine

**Comment by christian-bromann** [comment]
> I finally found the [commit](https://github.com/webdriverio/expect-webdriverio/commit/359155cd47f99a0c914f60354e956f82d63548f6#diff-38e3b0b46c9d69ee540371ca42b1e1492e271fa48ebffcc11f6885de396bcdf5R3) that introduced (on Dec 7th 2023)

This commit is a revert from a PR that wasn't fully working. So this line of code was there already before.

**Comment by Badisi** [comment]
@christian-bromann, ok my bad :)

After further investigation, I noticed that the last working version for me was `@wdio/globals @ 8.20.0`.

At that time, [`@wdio/globals/build/index.d.ts`](https://yarnpkg.com/package?q=%40wdio%2Fglobals&name=%40wdio%2Fglobals&version=8.20.0&file=%2Fbuild%2Findex.d.ts) was referencing types like this:
```ts
/// <reference types="./standalone.js" />
/// <reference types="types.js" />
```
Meaning **types.js** was wrongly referenced and not found (as it is one way up in the folder tree).
Resulting in 3, 4, 5 and 6 to never occur and Jasmine's expect to never be overrided.

------

Though, there is still something wrong with the current implementation as **jest-global** should never be imported if Jasmine integration is used.

**Comment by Badisi** [comment]
@christian-bromann, any thoughts on this ?

**Comment by christian-bromann** [comment]
I haven't been able to look into this, any contribution are appreciated!

**Comment by christian-bromann** [comment]
@Badisi any updates?

**Comment by rubenlg** [comment]
This hit me as well when I tried to write a custom matcher in Typescript with `@wdio` 8. Version 7 worked fine.

Here is the output of `npm ls @jest/types` to understand where it comes from:
```
MY_PROJECT
└─┬ @wdio/jasmine-framework@8.38.0
  └─┬ expect-webdriverio@4.13.0
    └─┬ expect@29.7.0
      ├─┬ jest-message-util@29.7.0
      │ └── @jest/types@29.6.3
      └─┬ jest-util@29.7.0
        └── @jest/types@29.6.3 deduped
```
It seems like `expect` has a hard dependency on jest. I worked around by creating my own wrapper around the `expect` function with types that suit me.

**Comment by christian-bromann** [comment]
@rubenlg can you provide a minimal reproducible example for this?

**Comment by rubenlg** [comment]
I tried to produce a minimal repro example. In order to make it as standard as possible, I started following the [Getting Started guide](https://webdriver.io/docs/gettingstarted), which I hadn't read in a while. At some point I noticed that wdio has (now? was it always like that?) its [own custom matcher API](https://webdriver.io/docs/custommatchers/). So it seems that I had been doing it wrong by using the standard jasmine API for installing custom matchers.

Anyway, that didn't work either. Even the example provided in the custom matcher documentation page fails with the same error as my code: 
` Error:  expect.extend is not a function`

I created a small repro repository here: https://github.com/rubenlg/webdriverio-jasmine-bug/tree/main

**Comment by christian-bromann** [comment]
Thanks @rubenlg any help on this would be appreciated!

**Comment by Badisi** [comment]
It seems that recent improvements in **wdio@9** had helped fix this issue.

But the Jasmine starter project generated by the cli is still broken (so it might need the following fix).

#### Solution
I had my example (test.e2e.ts) working in v9.0.9 with the following `tsconfig`:
```json
{
  "compilerOptions": {
    ...
    "types": [
      "node",
      "jasmine",
      "@wdio/globals/types",
      "expect-webdriverio/jasmine",
      "@wdio/jasmine-framework",
    ]
  }
}
```

**Comment by christian-bromann** [comment]
@Badisi would you be interested helping us getting a fix for the CLI out?

**Comment by Badisi** [comment]
@christian-bromann, ✅ done :  https://github.com/webdriverio/webdriverio/pull/13557
