### ISSUE TITLE
`BrowserObject` instance does not "understand" typings

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#3596]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
Instance `BrowserObject` does not "understand" typings. I meant that autocomplete does not work at all:
![image](https://user-images.githubusercontent.com/12623263/53240979-e374d080-36a8-11e9-83e3-17d9f2774014.png)
As I understand `BrowserObject` type looks like:
```js
// webdriverio.d.ts

type BrowserObject = WebDriver.ClientOptions & WebDriver.ClientAsync & WebdriverIOAsync.Browser;
``` 
So, autocomplete should show methods from these all types. Instead of it I see nothing. I don't know why it happens.

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
A clear and concise description.

**Comment by christian-bromann** [comment]
For WebStorm someone made a docs page to get autocompletion https://webdriver.io/docs/autocompletion.html .. does this work for you?

**Comment by CrispusDH** [comment]
> For WebStorm someone made a docs page to get autocompletion https://webdriver.io/docs/autocompletion.html .. does this work for you?

The issue that autocomplete for `Element` works correctly.

**Comment by christian-bromann** [comment]
So it works for the browser object but not for the element one?

**Comment by mgrybyk** [comment]
works for me in VSCode
![image](https://user-images.githubusercontent.com/25589559/53242181-4adc5180-36a4-11e9-839e-0f07da19ca2c.png)

**Comment by mgrybyk** [comment]
yes, confirming that it is not working in itelliji

**Comment by mgrybyk** [comment]
I'm seeing lots of similar issues submitted...

**Comment by CrispusDH** [comment]
I'm using WebStorm. Autocomplite works for Element and does NOT work for Browser.

**Comment by mgrybyk** [comment]
yes, I know, looks like some defect in itelliji IDEs. There are lots of issues saying the same

**Comment by christian-bromann** [comment]
@mgrybyk can you reference one?

**Comment by mgrybyk** [comment]
https://www.google.com/search?q=webstorm+typescript+duplicate+identifier

interesting thing is that once I've added some command there is error highlighting. But no autocomplete.

Maybe some configuration issue

**Comment by mgrybyk** [comment]
@CrispusDH I'll take care of this one

**Comment by mgrybyk** [comment]
@CrispusDH I've figured out what is the problem.

It is some defect in intelliji products. If there are lots of interface members autocomplete is not working, haha

**Comment by christian-bromann** [comment]
> We have 39 more members than it can handle :D

Darn 🙈 I guess we can close this one then?

**Comment by mgrybyk** [comment]
@christian-bromann we can do some "cleanup" of Client commands.
Not sure if we need all of them in browser object

**Comment by christian-bromann** [comment]
Since we don't know which session the user is running we can't strip any commands :-/

**Comment by mgrybyk** [comment]
@christian-bromann 
I mean that we can remove commands like 
- elementClick (because we have $("").click)
- getElementAttribute (same)

and I'm talking only about browser object, not Client interface

**Comment by CrispusDH** [comment]
```js
// webdriverio.d.ts

type BrowserObject = WebDriver.ClientOptions & WebDriver.ClientAsync & WebdriverIOAsync.Browser;
```
- `WebdriverIOAsync.Browse` has 21 properties
- `WebDriver.ClientAsync` has 186 properties **0_o**
- `WebDriver.ClientOptions` has 6 properties

Maybe we can somehow group up it in different way?

**Comment by mgrybyk** [comment]
There are some element related properties on browser level.
My proposal is to remove part of them or move to element level

**Comment by christian-bromann** [comment]
> browser.elementClick

if you have an elementID you can theoretically run that command

**Comment by mgrybyk** [comment]
hm, then our typings are not really valid `elementClick(): undefined;`

what if we create typings for different Client(s) and user will be able to import as much as needed?

```
    "types": [
      "node",
      "webdriverio",
      "@wdio/mocha-framework"
    ],
```

**Comment by mgrybyk** [comment]
One workaround is worse than another one :)

**Comment by christian-bromann** [comment]
Is itelliji interested in fixing this problem? I rather not want to have any circumstances because of a buggy IDE.

**Comment by CrispusDH** [comment]
I agree that it is strange to do something because of bug in IDE. But I'm not sure that merging all ~200 methods in one `BrowserObject` is a good path also.

**Comment by BorisOsipov** [comment]
>Is itelliji interested in fixing this problem? I rather not want to have any circumstances because of a buggy IDE.

@christian-bromann yes it is, if someone report bug to issue tracker with concise reproducible example.

**Comment by BorisOsipov** [comment]
second one, I didn't meet issues with webstorm typings, so are we sure there is no ide configuration issues with?

**Comment by AnnikaNissen** [comment]
Are you aure that this is an IntelliJ/IDE problem? 

I'm experiencing the same autocompletion issue in VS Code after updating to WebdriverIO v5.6.2 (coming from v5.4.17). To me it seems like this is related to the sync/async TypeScript changes (https://github.com/webdriverio/webdriverio/pull/3577). 

Also I'm also experiencing TypeScript compiling issues since the update: 
```
node_modules/@wdio/sync/webdriverio.d.ts:3:6 - error TS2300: Duplicate identifier 'BrowserObject'.

3 type BrowserObject = WebDriver.ClientOptions & WebDriver.Client & WebdriverIO.Browser;
       ~~~~~~~~~~~~~

  node_modules/webdriverio/webdriverio.d.ts:3:6
    3 type BrowserObject = WebDriver.ClientOptions & WebDriver.ClientAsync & WebdriverIOAsync.Browser;
           ~~~~~~~~~~~~~
    'BrowserObject' was also declared here.
```

I added the sync-types to my tsconfig as described in the documentation:
```
{
  "include": [
    "./source/**/*"
  ],
  "compilerOptions": {
    /* Basic Options */
    "target": "ES2015",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": [
      "es2015", "dom"
    ],                             /* Specify library files to be included in the compilation. */
    "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
     "outDir": "./build",                        /* Redirect output structure to the directory. */
     "rootDir": "./source",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */

    /* Strict Type-Checking Options */
    "strict": false,                           /* Enable all strict type-checking options. */

    /* Module Resolution Options */
    //"typeRoots": [
    //  "node_modules/@types"
    // ],                       /* List of folders to include type definitions from. */
    "types": ["node", "@wdio/sync"],                           /* Type declaration files to be included in compilation. */
    "esModuleInterop": true,                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */

    /* Experimental Options */
     "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
     "emitDecoratorMetadata": true         /* Enables experimental support for emitting type metadata for decorators. */
  }
}
```

It seems like the Typescript compiler gets confused about the typings being in `webdriverio`-package AND `@wdio/sync`-package. Any ideas on how to resolve this?

**Comment by mgrybyk** [comment]
@AnnikaNissen 

Are you using @wdio/sync version?
Are you importing webdriverio anywhere? ex import * as webdriverio from "webdriverio"

**Comment by AnnikaNissen** [comment]
@mgrybyk 

Yes, I'm using WebdriverIO with the `@wdio/sync` package. I actually had imports from webdriverio without being aware of them - my compiler issues are gone since I removed all of them. 

It seems like the VS code code completion is still confused. I'll try to investigate that a bit more during the day and give an update on that asap.

**Comment by mgrybyk** [comment]
@AnnikaNissen don't forget restarting VSCode after changing typings in tsconfig

**Comment by AnnikaNissen** [comment]
@mgrybyk 

My code completion stays broken, also after restarting VS Code. Here is what I'm experiencing:

* `browser` is known and is completed. When pressing `F12` on `browser`, the type definition file in the `@wdio/sync` package is opened. But after `browser`, the completion stops. Methods on browser are not completed.
![screen shot 2019-02-26 at 09 13 32](https://user-images.githubusercontent.com/9281006/53397274-0653fd00-39a7-11e9-9679-245e73ad6bc4.png)
* When opening `node_modules/@wdio/sync/webdriverio.d.ts` file, VS Code shows some issues, fx with the `BrowserObject`-type
![screen shot 2019-02-26 at 09 17 00](https://user-images.githubusercontent.com/9281006/53397420-6ba7ee00-39a7-11e9-9f6d-079c9132b6df.png)
* When continuing coding, there is no more code completion, fx on an element
![screen shot 2019-02-26 at 09 14 06](https://user-images.githubusercontent.com/9281006/53397585-c7727700-39a7-11e9-846b-38c800ea3fed.png)
* Elements saved in variables are considered to have type `any`
![screen shot 2019-02-26 at 09 14 29](https://user-images.githubusercontent.com/9281006/53397610-d6592980-39a7-11e9-98b2-c1198b9d2972.png)

Any ideas on how this could be fixed?

My `tsconfig.json` looks like this (and the file edited above is located in `test-desktop/pages/example.page.ts`):

```
{
    "exclude": [
      "./source/**/*",
      "./build/**/*"
    ],
    "include": [
        "./test*/**/*",
        "./shared/**/*",
        "./datageneration/**/*"
    ],
    "compilerOptions": {
        "target": "ES2015",
        "module": "commonjs",
        "lib": [
            "ES2015",
            "dom"
        ],
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": ["node", "@wdio/sync", "@types/chai"],
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

**Comment by mgrybyk** [comment]
Try removing typeRoots": [
            "node_modules/@types"
        ],

And all imports of webdriverio in the code.

**Comment by AnnikaNissen** [comment]
@mgrybyk 

Unfortunately that doesn't help.

**Comment by mgrybyk** [comment]
I need reproducible example then

**Comment by CrispusDH** [comment]
@AnnikaNissen I think will be better to create separated issue

**Comment by AnnikaNissen** [comment]
@mgrybyk Sorry - I can#t share the code I'm working on right now. Will look into creating a reproducible example as soon as I have some time.

@CrispusDH Will do, as soon as I have something reproducible 👍

**Comment by mgrybyk** [comment]
@CrispusDH can we close this? It if intelliji defect not related to webdriverio.

**Comment by CrispusDH** [comment]
I think yes. Also, it would be great to get how to decrease amount of methods for `Browser` object. Currently, I don't have good thoughts.

**Comment by BorisOsipov** [comment]
>It is some defect in intelliji products. If there are lots of interface members autocomplete is not working, haha

@mgrybyk can you link to ide bug or particular SO question?

**Comment by mgrybyk** [comment]
As it we had figured out the problem is that there are too many methods for browser object.

If someone can look for this issue or submit new one it would be great.
I'm not using intelliji products with js/ts.
