### ISSUE TITLE
Autocompletion is broken since update to 5.6.x when using `@wdio/sync`

### ISSUE THREAD

**Issue by AnnikaNissen** [webdriverio/webdriverio#3646]
**Environment:**
 - **WebdriverIO version:** 5.6.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.9.4
 - **NPM version:** 5.6.0
 - **Browser name and version:** not relevant
 - **Platform name and version:** not relevant
 - **Additional wdio packages used (if applicable):** @wdio/sync, @wdio/spec, @wdio/selenium-standalone

A repoducable example of for this bug report can be found here: https://github.com/AnnikaNissen/webdriverio-test

**Config of WebdriverIO**
See [wdio.conf.js](https://github.com/AnnikaNissen/webdriverio-test/blob/master/wdio.conf.js)

**Describe the bug**  
Since I updated to v5.6.x (coming from v5.4.17) I'm experiencing autocompletion problems in my test projects using VS Code, as already described [here](https://github.com/webdriverio/webdriverio/issues/3596#issuecomment-466955088). 
To ensure that the autocompletion problem is not related to the typescript setup in that specific project, I created a clean test project, where I'm experiencing the same autocompletion issues.

**To Reproduce**
Steps to reproduce the behaviour:
* Checkout the example project from https://github.com/AnnikaNissen/webdriverio-test
* Run `npm install`
* Run `npm run test` and see one test passing (-> the code works as expected)
* Open the project folder in VS Code (I'm using v1.31.1 on Mac, but it also occurs on Windows)
* Open `test/specs/basic.ts` and try some editing

**Expected behavior**

When editing the file `test/specs/basic.ts`, I expect to get autocompletion for WebdriverIO commands, fx. when using the `browser` object. But no autocompletion is shown:

Methods on `browser` aren't completed:
![screen shot 2019-02-28 at 10 58 50](https://user-images.githubusercontent.com/9281006/53562577-fd535f00-3b51-11e9-9fd5-e1c57df5231f.png)

Methods on elements aren't completed:
![screen shot 2019-02-28 at 11 00 05](https://user-images.githubusercontent.com/9281006/53562586-017f7c80-3b52-11e9-9206-9fd1c6bb064b.png)

When hovering `borwser`, it has a type of `any`:
![screen shot 2019-02-28 at 12 21 52](https://user-images.githubusercontent.com/9281006/53563172-83bc7080-3b53-11e9-852c-1145df7b511f.png)

Autocompletion for other functions, like fx for mocha is working fine:
![screen shot 2019-02-28 at 10 59 20](https://user-images.githubusercontent.com/9281006/53562608-12c88900-3b52-11e9-8223-95eef32eecb8.png)

**Additional context**

The [`tsconfig.json`](https://github.com/AnnikaNissen/webdriverio-test/blob/master/tsconfig.json) for the project looks like this (following your guide on usage of TypeScript): 
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": [ "./*" ],
            "src/*": ["./src/*"]
        },
        "types": ["node", "@wdio/sync", "@wdio/mocha-framework"]
    },
    "include": [
        "./src/**/*.ts"
    ]
}
```

I guess that this issue is related to the changes introduced by https://github.com/webdriverio/webdriverio/pull/3577 

It would be really, really nice to get the autocompletion back, as it makes writing of tests that much easier, especially for developers that don't work with UI tests on a day-to-day basis. 

If you have difficulties reproducing this issues or any questions, just ask.

Thanks in advance,
Annika

**Comment by christian-bromann** [comment]
ping @mgrybyk @CrispusDH

**Comment by mgrybyk** [comment]
Taking a look

**Comment by mgrybyk** [comment]
@AnnikaNissen just checked out your project. You have problems in tsconfig.
Change /src/ path to /test/ it to 
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": [ "./*" ],
            "src/*": ["./test/*"]
        },
        "types": ["node", "@wdio/sync", "@wdio/mocha-framework"]
    },
    "include": [
        "./test/**/*.ts"
    ]
}
```

No additional changes were made.
![image](https://user-images.githubusercontent.com/25589559/53565999-4eb41c00-3b5b-11e9-8d10-3445b2eed57b.png)

**Comment by mgrybyk** [comment]
in order to avoid such problems compile your sources with `tsc`. It will printout problems you have, correct them first and autocomplete will work.
Also, make sure to call `tsc` of proper version. Maybe you have TypeScript installed globally of different version.

```
./node_modules/.bin/tsc
error TS18003: No inputs were found in config file '/Users/m/sources/wdio-defects/webdriverio-test/tsconfig.json'. Specified 'include' paths were '["./src/**/*.ts"]' and 'exclude' paths were '[]'.
```

**Comment by christian-bromann** [comment]
@mgrybyk thanks for taking a look. Closing then.

**Comment by mgrybyk** [comment]
![image](https://user-images.githubusercontent.com/25589559/53566401-558f5e80-3b5c-11e9-9e9b-2b8647806a2c.png)
![image](https://user-images.githubusercontent.com/25589559/53566413-5d4f0300-3b5c-11e9-8987-fce0fc0501ab.png)
![image](https://user-images.githubusercontent.com/25589559/53566438-75268700-3b5c-11e9-8226-6d8abec14f32.png)

**Comment by AnnikaNissen** [comment]
@mgrybyk 

Thanks for having a look! I already had changed the include path to `test/` put forgot to push it - my fault! So changing that didn't help. 

But I actually figured it out now and it works perfectly now: 
Changing the TypeScript version used by VS Code to "Use workspace version" (which is v3.3.3333 in my case) did the trick. Before VS Code was configured to use v3.1.x of TypeScript.

Thanks for opening my eyes and have a nice evening :)!
