### ISSUE TITLE
[🐛 Bug]: Test not starting on v8

### ISSUE THREAD

**Issue by ReshailLean** [webdriverio/webdriverio#9288]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8

### Node.js Version

16.13.2

### Mode

Standalone Mode

### What happened?

Trying to migrate from v7 to v8. The tests start and get stuck without any error.

My dependencies

    "@wdio/allure-reporter": "^8.0.0",
    "@wdio/appium-service": "^8.0.0",
    "@wdio/cli": "^8.0.0",
    "@wdio/local-runner": "^8.0.0",
    "@wdio/mocha-framework": "^8.0.0",
    "@wdio/selenium-standalone-service": "^8.0.0",
    "@wdio/spec-reporter": "^8.0.0",

### What is your expected behavior?

Test should run just as they did with v7

### How to reproduce the bug.

Setup a fresh webriver.io project with v8 and run the test scripts

### Relevant log output

```typescript
`2022-12-02T10:07:44.576Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2022-12-02T10:07:44.579Z INFO @wdio/cli:launcher: Run onPrepare hook
Initializing Chrome Service With Port - 5010
2022-12-02T10:07:44.605Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.0)
2022-12-02T10:07:44.608Z INFO chromedriver: Start Chromedriver (/Users/reshail/lean-test-framework/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=5010 --url-base=/
2022-12-02T10:07:44.629Z INFO chromedriver: Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 5010
2022-12-02T10:07:44.630Z INFO chromedriver: Only local connections are allowed.
2022-12-02T10:07:44.631Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-12-02T10:07:44.631Z INFO chromedriver: ChromeDriver was started successfully.
2022-12-02T10:07:44.724Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 144ms
2022-12-02T10:07:44.727Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-12-02T10:07:44.727Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-12-02T10:07:44.728Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,config/wdio.conf.js`

When I force quit it

Ended WebDriver sessions gracefully after a SIGINT signal was received!
2022-12-02T10:12:15.904Z INFO @wdio/local-runner: Shutting down spawned worker
[0-0] 2022-12-02T10:12:15.904Z INFO @wdio/local-runner: Received SIGINT, giving process 5000ms to shutdown gracefully
[0-0] 2022-12-02T10:12:15.907Z INFO @wdio/local-runner: Run worker command: endSession
[0-0] 2022-12-02T10:12:15.908Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'sessionId')
[0-0]     at Runner.endSession (file:///Users/reshail/lean-test-framework/node_modules/@wdio/runner/build/index.js:364:50)
[0-0]     at process.<anonymous> (file:///Users/reshail/lean-test-framework/node_modules/@wdio/local-runner/build/run.js:18:22)
[0-0]     at process.emit (node:events:402:35)
[0-0]     at process.emit (node:domain:475:12)
[0-0]     at emit (node:internal/child_process:917:12)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:84:21)
2022-12-02T10:12:15.926Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ReshailLean** [comment]
I must be doing something wrong here because no one else seems to be complaining but I can not figure out what is missing. Would be grateful if someone can point me towards my mistake

**Comment by christian-bromann** [comment]
@ReshailLean did you update the version from an existing project? Is it possible to create a reproducible example?

**Comment by sankalpguptasymphony** [comment]
> @ReshailLean did you update the version from an existing project? Is it possible to create a reproducible example?

I am getting a different error, it's running fine with V7 but when I updated it to V8, it stopped working.

Dependencies - 

    "@babel/cli": "^7.19.3",
    "@babel/core": "^7.20.5",
    "@babel/preset-env": "^7.20.2",
    "@babel/register": "^7.18.9",
    "@wdio/cli": "^8.0.5",
    "@wdio/cucumber-framework": "^8.0.2",
    "@wdio/local-runner": "^8.0.5",
    "@wdio/selenium-standalone-service": "^8.0.2",
    "fs-extra": "^11.1.0",
    "node": "^16.18.1",
    "wdio-wait-for": "^3.0.1",
    "webdriverio": "^8.0.5"

Error - SeleniumStandalone.start is not a function

Execution of 1 workers started at 2022-12-05T09:01:09.420Z

2022-12-05T09:01:09.592Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-12-05T09:01:13.766Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: SeleniumStandalone.start is not a function
    at SeleniumStandaloneLauncher.onPrepare (file:///D:/SFX-Automation/node_modules/@wdio/selenium-standalone-service/build/launcher.js:92:42)
    at file:///D:/SFX-Automation/node_modules/@wdio/cli/build/utils.js:41:17
    at async Promise.all (index 0)
    at Launcher.run (file:///D:/SFX-Automation/node_modules/@wdio/cli/build/launcher.js:82:13)

Continue...
2022-12-05T09:01:13.790Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-12-05T09:01:13.793Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2022-12-05T09:01:14.820Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///D:/SFX-Automation/features/folders/foldersPage.feature
[0-0] 2022-12-05T09:01:16.215Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-12-05T09:01:16.330Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2022-12-05T09:01:16.331Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true,
[0-0]     'goog:chromeOptions': { args: [Array], prefs: [Object] }
[0-0]   }
[0-0] }
[0-0] 2022-12-05T09:01:16.360Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444
[0-0]     at ClientRequest.<anonymous> (file:///D:/SFX-Automation/node_modules/webdriver/node_modules/got/dist/source/core/index.js:789:107)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:525:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:494:9)
[0-0]     at Socket.emit (node:events:513:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:157:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[0-0] 2022-12-05T09:01:16.360Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/wd/hub", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at startWebDriverSession (file:///D:/SFX-Automation/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at Function.newSession (file:///D:/SFX-Automation/node_modules/webdriver/build/index.js:24:45)
[0-0]     at remote (file:///D:/SFX-Automation/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at Runner._startSession (file:///D:/SFX-Automation/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at Runner._initSession (file:///D:/SFX-Automation/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at Runner.run (file:///D:/SFX-Automation/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] FAILED in chrome - file:///D:/SFX-Automation/features/folders/foldersPage.feature
2022-12-05T09:01:16.515Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-12-05T09:01:16.516Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:07

**Comment by ReshailLean** [comment]
@christian-bromann I have tried with a new project and also tried updating my current project.

Steps I used are from here https://webdriver.io/docs/gettingstarted/
1) Setup fresh project
2) Run the example tests

I get the same issue, it gets stuck here

`Initializing Chrome Service With Port - 5010
2022-12-02T10:07:44.605Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.0)
2022-12-02T10:07:44.608Z INFO chromedriver: Start Chromedriver (/Users/reshail/lean-test-framework/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=5010 --url-base=/
2022-12-02T10:07:44.629Z INFO chromedriver: Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 5010
2022-12-02T10:07:44.630Z INFO chromedriver: Only local connections are allowed.
2022-12-02T10:07:44.631Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-12-02T10:07:44.631Z INFO chromedriver: ChromeDriver was started successfully.
2022-12-02T10:07:44.724Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 144ms
2022-12-02T10:07:44.727Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-12-02T10:07:44.727Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-12-02T10:07:44.728Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,config/wdio.conf.js``

If I revert to v7 it starts to work. Any idea why that might be happening?

**Comment by christian-bromann** [comment]
@ajeetd I can't reproduce it following your steps. Can you make sure to run with the following command:

```sh
npm init wdio@latest .
```

The `@latest` is important as we have some changes in `create-wdio` too.

@ReshailLean can you describe the concrete ways to reproduce this?

**Comment by Diazole** [comment]
I am also receiving `Error - SeleniumStandalone.start is not a function` on v8.

```
2022-12-06T11:22:07.159Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2022-12-06T11:22:07.253Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2022-12-06T11:22:07.253Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-12-06T11:22:07.766Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: SeleniumStandalone.start is not a function
    at SeleniumStandaloneLauncher.onPrepare (file:///.../@wdio/selenium-standalone-service/build/launcher.js:92:42)
    at async file:///.../@wdio/cli/build/utils.js:42:17
    at async Promise.all (index 0)
    at async Launcher.run (file:///.../@wdio/cli/build/launcher.js:82:13)
```

`npm init wdio@latest .` produces the same error.

**Comment by christian-bromann** [comment]
@ReshailLean best thing would be to create a GitHub repo that I can pull and run to reproduce the error.

**Comment by sankalpguptasymphony** [comment]
> I am also receiving `Error - SeleniumStandalone.start is not a function` on v8.
> 
> ```
> 2022-12-06T11:22:07.159Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
> 2022-12-06T11:22:07.253Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
> 2022-12-06T11:22:07.253Z INFO @wdio/cli:launcher: Run onPrepare hook
> 2022-12-06T11:22:07.766Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
> TypeError: SeleniumStandalone.start is not a function
>     at SeleniumStandaloneLauncher.onPrepare (file:///.../@wdio/selenium-standalone-service/build/launcher.js:92:42)
>     at async file:///.../@wdio/cli/build/utils.js:42:17
>     at async Promise.all (index 0)
>     at async Launcher.run (file:///.../@wdio/cli/build/launcher.js:82:13)
> ```
> 
> `npm init wdio@latest .` produces the same error.

@Diazole I tested it again today and this issue is not occurring anymore with webdriverIO 8.0.9, please give it a try.

**Comment by ReshailLean** [comment]
@christian-bromann here is a github repo to reproduce the issue: https://github.com/ReshailAlvi/WebDriverV8

**Comment by darkartswizard** [comment]
I retried on Windows with my TS project.
Still getting no response after upgrading to 8.0.9 

```
Upgrading D:\repos\Test-Automation-with-WebdriverIO\package.json
[====================] 13/13 100%

 @wdio/allure-reporter    ^8.0.7  →  ^8.0.8
 @wdio/cli                ^8.0.7  →  ^8.0.9
 @wdio/jasmine-framework  ^8.0.7  →  ^8.0.9
 @wdio/local-runner       ^8.0.7  →  ^8.0.9
 @wdio/mocha-framework    ^8.0.7  →  ^8.0.9
 @wdio/spec-reporter      ^8.0.7  →  ^8.0.8
 typescript               ^4.9.3  →  ^4.9.4

Run npm install to install new versions.

qtpmgrossman@MSI MINGW64 /d/repos/Test-Automation-with-WebdriverIO (chapter-4)
$ npm i

added 69 packages, changed 9 packages, and audited 607 packages in 9s

118 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

qtpmgrossman@MSI MINGW64 /d/repos/Test-Automation-with-WebdriverIO
$ npm run wdio

> wdio@1.0.0 wdio
> wdio run test/wdio.conf.ts

qtpmgrossman@MSI MINGW64 /d/repos/Test-Automation-with-WebdriverIO
```

**Comment by christian-bromann** [comment]
> Still getting no response after upgrading to 8.0.9

@darkartswizard this is related to #9334

**Comment by christian-bromann** [comment]
The issue that the worker doesn't start should be fixed now, please let me know if you still experience this with the latest release.

**Comment by matthew2564** [comment]
I am receiving this this error after updating to v8.

```
[0-6] 2023-11-27T17:06:48.105Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read properties of undefined (reading 'sessionId')
[0-6]     at Runner.endSession (file:///Users/matt/wdio-project/node_modules/@wdio/runner/build/index.js:386:50)
[0-6]     at process.<anonymous> (file:///Users/matt/wdio-project/node_modules/@wdio/local-runner/build/run.js:27:22)
[0-6]     at process.emit (node:events:526:35)
[0-6]     at process.emit (node:domain:488:12)
[0-6]     at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/matt/wdio-project/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
[0-6]     at emit (node:internal/child_process:951:14)
[0-6]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

System versions
```
» node -v                                                                                                                           
v20.9.0
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
» npm -v 
10.1.0
```

Using `v8.24.0` of `@wdio/*/` packages.

**Comment by christian-bromann** [comment]
@matthew2564 please make sure you update all WebdriverIO packages to `latest`

**Comment by matthew2564** [comment]
Installed the latest version, same issue.

**Comment by christian-bromann** [comment]
Can you provide a reproducible example then?

**Comment by mateuszm22** [comment]
@christian-bromann 
The issue is still reproducing.
node: v20.11.1
npm: 8.19.2

Reproduction steps:
1. Use command: npm init wdio@latest ./path/to/new/project
2. Go through the installer and use: mocha, ts, chromedriver
3. After installation do: npm run wdio

Actual result:
Execution of 1 workers started at 2024-03-04T23:31:57.936Z

2024-03-04T23:31:57.969Z INFO @wdio/local-runner: Shutting down spawned worker
2024-03-04T23:31:58.226Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-03-04T23:31:58.226Z INFO @wdio/local-runner: shutting down
TypeError in "undefined"
TypeError: this.runner.initialise is not a function
    at Launcher.run (file:/node_modules/@wdio/cli/build/launcher.js:76:31)

**Comment by mateuszm22** [comment]
@christian-bromann
Sure, here you go.
There is a log.txt file with my cmd output.
https://github.com/mateuszm22/9288

**Comment by LikaKse** [comment]
таже ошибка, обновила ноду до 18  при запуске теста через npx wdio run wdio.conf.js ошибка
```
ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://e2e-selenium:4444/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at startWebDriverSession (/e2e/node_modules/webdriver/build/utils.js:72:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.newSession (/e2e/node_modules/webdriver/build/index.js:42:45)
    at remote (/e2e/node_modules/webdriverio/build/index.js:73:22)
    at Runner._startSession (/e2e/node_modules/@wdio/runner/build/index.js:223:56)
    at Runner._initSession (/e2e/node_modules/@wdio/runner/build/index.js:176:25)
    at Runner.run (/e2e/node_modules/@wdio/runner/build/index.js:88:19)

```
