### ISSUE TITLE
[🐛 Bug]: Jest .not modifier assertion no longer working

### ISSUE THREAD

**Issue by ashil88** [webdriverio/webdriverio#10606]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### What happened?

After updating to v8.11.2 previous passing negative assertions
`await expect(someString).not.toContain(subString);`
`await expect(someVal).not.toBe(someOtherValue);`

are now failing with the following error
`TypeError: fn(...).negativeCompare is not a function`

Possibly related to this PR https://github.com/webdriverio/webdriverio/pull/10533

### What is your expected behavior?

These tests should continue to pass as before.

### How to reproduce the bug.

Upgrade to 8.11.2 and test negative assertion
`await expect(someString).not.toContain(subString);`

### Relevant log output

```typescript
`TypeError: fn(...).negativeCompare is not a function`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
