### ISSUE TITLE
[4.0] problems chaining waitUntil

### ISSUE THREAD

**Issue by parisholley** [webdriverio/webdriverio#1063]
Not really sure how to reproduce, i tried writing unit test cases in the project but it always passes. I have waitUntil calls back to back with a function as a parameter that returns a promise (http call) that fails for a few passes, then eventually returns true.

problems appears to be that when i return fulfill(true) from my promise, instead of returning client to the next call int he chain, it returns "true" and I get waitUntil is not a function error. Works fine in 3.4, but not in 4.0 when running from the build/ directory.

**Comment by parisholley** [comment]
should also note that this is not an issue when using the client directly. only when going through wdio

**Comment by christian-bromann** [comment]
Can you provide an example script?

**Comment by parisholley** [comment]
this is the test case i wrote to reproduce (which does not fail) which mimics the behavior of my test script

```
    it.only('should chain without error', async function () {
        let invokes = 0;

        let res = await this.client
            .waitUntil(() => new Promise((r) => {
                if(invokes == 1){
                    return r(true);
                }
                invokes++;
                r(false);
            }))
            .waitUntil(() => new Promise((r) => {
                r(true);
            }))
            .waitUntil(() => new Promise((r) => {
                if(invokes == 2){
                    return r(true);
                }
                invokes++;
                r(false);
            }))
            .waitUntil(() => new Promise((r) => {
                r('foobar');
            }))
            .then(function(){
                return 'foobaz'
            })

        res.should.be.equal('foobaz')
    })
```

**Comment by parisholley** [comment]
@christian-bromann i also just pasted that as a replacement in my project with my script, same behavior. the program exists before the second waitUntil is invoked.

using the following versions
"webdriverio": "git://github.com/parisholley/webdriverio.git#build" (just master with build directory committed)
"wdio-mocha-framework": "0.2.4"

**Comment by parisholley** [comment]
also I am using node v0.12.7 and npm 3.5.2. this problem seems to occur with any of the wait commands. i can reproduce by putting waitForExist() back to back.

one thing I am noticing in my testing when i stick a bunch of console statements everywhere is there are differences in the call behavior between wdio and direct. for example, i put a log command inside unit.ift within webdriver.io like so:

```
        commandGroup[name] = function () {
            console.log('group =', name);
```

when calling the driver directly, i see this output prior to anything else happening

```
group = init
group = url
group = waitForExist
group = waitForExist
group = execute
group = waitUntil
group = waitUntil
group = end
```

which is what i expect, as it should be building a promise chain upfront, then executing each command as it goes. however in wdio, that does not happen, you only see the group = logs as the test executes.

**Comment by christian-bromann** [comment]
This:

```js
it.only('should chain without error', async function () {
```

does not switch tests to be async again. It will be a `sync` property in your conf file

**Comment by christian-bromann** [comment]
@parisholley please update wdio packages and add `sync: false` to your wdio.conf.js. It should work now.

**Comment by parisholley** [comment]
@christian-bromann works, thanks!
