### ISSUE TITLE
browser.getTabIds() not working in v5

### ISSUE THREAD

**Issue by caweidmann** [webdriverio/webdriverio#4279]
**Environment:**
 - **WebdriverIO version:** 5.11.0
 - **Mode:** Standalone
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** Ubuntu

**Describe the bug**
I was using `browser.getTabIds()` previously. After upgrading to v5 I get the following error:
```
TypeError: browser.getTabIds is not a function
```
On v4 I can see the method here: http://v4.webdriver.io/v3.4/api/window/getTabIds.html

For v5 I am unable to see the method or what method replaces it or how to get the tabs and switch tabs, e.g. via `browser.switchTab()`.

**To Reproduce**
Use `browser.getTabIds()` in a step with webdriverio v5.

**Expected behavior**
There should be documentation on how to migrate from v4 to v5 for `browser.getTabIds()`.

**Comment by mgrybyk** [comment]
https://webdriver.io/docs/api/webdriver.html#getwindowhandles

Please use gitter for such questions

**Comment by caweidmann** [comment]
Cool, thanks.
