### ISSUE TITLE
[🐛 Bug]: TypeError: this[#browser].on is not a function

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#13809]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.2

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    'wdio:enforceWebDriverClassic': true,
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: [
        '--disable-backgrounding-occluded-windows',
        '--window-size=1980,1080',
        '--lang=fr_FR.UTF-8',
        '--disable-search-engine-choice-screen',
      ],
    },
  },
```

### What happened?

An error is displayed at startup of tests

### How to reproduce the bug.

Just launch a test.
Concern this below code:
![image](https://github.com/user-attachments/assets/4a54344c-7faa-43cb-b16c-48196efec743)

### Relevant log output

```typescript
[0-0] 2024-10-28T10:40:03.961Z ERROR @wdio/runner: TypeError: this[#browser].on is not a function
[0-0]     at new ContextManager (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriverio\build\index.js:2995:19)
[0-0]     at getContextManager (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriverio\build\index.js:2983:22)
[0-0]     at remote (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriverio\build\index.js:7472:5)
[0-0]     at async Runner._startSession (file:///C:/2-gitlab/insight/quality/end-to-end-tests-wdio/node_modules/@wdio/runner/build/index.js:781:23)
[0-0]     at async Runner.run (file:///C:/2-gitlab/insight/quality/end-to-end-tests-wdio/node_modules/@wdio/runner/build/index.js:642:20)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lukerj1988** [comment]
I have just had the same issue crop up today. 
Node 22.7.0, WebdriverIO: 9.2.1
```[0-0] 2024-10-28T14:51:53.816Z ERROR @wdio/runner: TypeError: this[#browser].on is not a function
[0-0]     at new ContextManager (C:\Users\cs1lrj\Documents\automation\functional\cis-rehosting-automation-wdio\node_modules\webdriverio\build\index.js:2995:19)
[0-0]     at getContextManager (C:\Users\cs1lrj\Documents\automation\functional\cis-rehosting-automation-wdio\node_modules\webdriverio\build\index.js:2983:22)
[0-0]     at remote (C:\Users\cs1lrj\Documents\automation\functional\cis-rehosting-automation-wdio\node_modules\webdriverio\build\index.js:7472:5)
[0-0]     at async Runner._startSession (file:///C:/Users/cs1lrj/Documents/automation/functional/cis-rehosting-automation-wdio/node_modules/@wdio/runner/build/index.js:781:23)
[0-0]     at async Runner.run (file:///C:/Users/cs1lrj/Documents/automation/functional/cis-rehosting-automation-wdio/node_modules/@wdio/runner/build/index.js:642:20)```

**Comment by unickq** [comment]
Have the same with wdio 9.5.0

```js
{
      platformName: "iOS",
      "appium:deviceName": process.env.ios_model || "iPhone 16",
      "appium:platformVersion": process.env.ios_version || "18.1",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "XCUITest",
      "appium:newCommandTimeout": 480,
      "appium:launchTimeout": 300_000,
      "appium:wdaLaunchTimeout": 150_000,
      "appium:app": join(process.cwd(), "apps", "dev.app"),
      "appium:udid": process.env.CI ? process.env.UDID : "",
    }
```

```
[0-0] 2024-12-31T13:57:29.164Z ERROR @wdio/runner: TypeError: this[#browser].getContext is not a function
[0-0]     at ContextManager.initialize (/Users/unickq/git/ui-mobile-tests/node_modules/webdriverio/build/index.js:3121:43)
[0-0]     at remote (/Users/unickq/git/ui-mobile-tests/node_modules/webdriverio/build/index.js:8075:33)
[0-0]     at async Runner._startSession (file:///Users/unickq/git/ui-mobile-tests/node_modules/@wdio/runner/build/index.js:809:23)
[0-0]     at async Runner.run (file:///Users/unickq/git/ui-mobile-tests/node_modules/@wdio/runner/build/index.js:670:20)
```

![image](https://github.com/user-attachments/assets/6297ad14-6919-46e3-a011-9f3884abbae7)

**Comment by unickq** [comment]
Have the same with wdio 9.5.0; however, it doesn't block anything. cc @christian-bromann 

```js
{
      platformName: "iOS",
      "appium:deviceName": process.env.ios_model || "iPhone 16",
      "appium:platformVersion": process.env.ios_version || "18.1",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "XCUITest",
      "appium:newCommandTimeout": 480,
      "appium:launchTimeout": 300_000,
      "appium:wdaLaunchTimeout": 150_000,
      "appium:app": join(process.cwd(), "apps", "dev.app"),
      "appium:udid": process.env.CI ? process.env.UDID : "",
    }
```

```
[0-0] 2024-12-31T13:57:29.164Z ERROR @wdio/runner: TypeError: this[#browser].getContext is not a function
[0-0]     at ContextManager.initialize (/Users/unickq/git/ui-mobile-tests/node_modules/webdriverio/build/index.js:3121:43)
[0-0]     at remote (/Users/unickq/git/ui-mobile-tests/node_modules/webdriverio/build/index.js:8075:33)
[0-0]     at async Runner._startSession (file:///Users/unickq/git/ui-mobile-tests/node_modules/@wdio/runner/build/index.js:809:23)
[0-0]     at async Runner.run (file:///Users/unickq/git/ui-mobile-tests/node_modules/@wdio/runner/build/index.js:670:20)
```

![image](https://github.com/user-attachments/assets/6297ad14-6919-46e3-a011-9f3884abbae7)

**Comment by AlanXavierKlein** [comment]
I started experiencing the same issue after upgrading WebDriverIO from v7 to v9.
Although it doesn't block the test execution, the generated report does not display the device, OS, and app used. (It seems to retrieve this information from this[#browser].getContext).
Environment: Node 20, WebDriverIO: 9.4.5, multiple-cucumber-html-reporter: 3.8.0.

**Comment by christian-bromann** [comment]
@unickq @AlanXavierKlein can you provide a minimal reproducible example?

**Comment by MaxAllianov** [comment]
Joining the waiting list for the fix
Don't know the reproducing steps but I am also using wdio + appium and have 'appium:autoWebview': true capability possibly its a key

![Image](https://github.com/user-attachments/assets/373d87ee-fd08-464e-84f3-69ac5710769b)
![Image](https://github.com/user-attachments/assets/7228b5bf-16bf-41b5-a157-e3b7e4035358)

**Comment by christian-bromann** [comment]
@MaxAllianov we plan to release a fix this week.
