### ISSUE TITLE
[🐛 Bug]: Image comparison shows error Typeerror: browser.checkElement() is not a function

### ISSUE THREAD

**Issue by staizen-ara** [webdriverio/webdriverio#10361]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

16.15

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
browser: Chrome,
browserVersion: latest,
platformName: Apple M1
}
```

### What happened?

I updated @wdio/selenium-standalone-service to ^8.0.3 because of this >>> https://github.com/webdriverio/webdriverio/issues/8944, however upon doing that I encountered Typeerror: browser.checkElement() is not a function error for my image comparison tests.

Error: 1/2 expected conditions not met after waiting for 5000:
                Expression: ElementConditions
                
                  Condition: Displayed 
                  Selector: {selector}
                  Result: Success
                  Expected: true
                  Actual: true
                  ------------------------------
                  Condition: SnapshotMatch [default/chrome-headless/component/02-01.png] 
                  Selector:{selector}
                  Result: Failed
                  Expected: Within 0.15% difference
                  Actual: TypeError: browser.checkElement is not a function

### What is your expected behavior?

Expecting the image comparison to perform as expected

### How to reproduce the bug.

Using an Apple M1, have your webdriverio version to 7.24, and update @wdio/selenium-standalone-service to ^8.0.3, update package.lock, then run your tests in github actions.

### Relevant log output

```typescript
I couldn't perform logs because node16 and m1 is having issues on using wdio-image-comparison-service locally, so I have skipped my image comparison locally for this.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> have your webdriverio version to 7.24, and update @wdio/selenium-standalone-service to ^8.0.3

We do not support have different major version of WebdriverIO installed. Please make sure that all your packages are either on v8 or v7 or in case of community package verify that it supports the WebdriverIO version you are using.

I will close this as this seems to be a setup issue. Happy to answer further questions. Join our  [Support Chat on Discord](https://discord.webdriver.io) for further questions as well.

**Comment by Lynxerge** [comment]
Hey there, i'm working with wdio 8.24.3, all my packages are on the same major version but im still getting this. Using wdio-image-comparison-service to do browser.checkElement but it throws this error, is it maybe that the wdio version is too high? Thanks!

**Comment by christian-bromann** [comment]
@Lynxerge mind raising an issue in the `wdio-image-comparison-service`? It hasn't seen updates for 7 month so it could be that something is up. Mind sharing your stack trace?
