### ISSUE TITLE
Unexpected `await` of a non-Promise

### ISSUE THREAD

**Issue by denchen** [webdriverio/webdriverio#6407]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.12.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** chromedriver 88.0.0
 - **Platform name and version:** MacOS 11.2
 - **Additional wdio packages used (if applicable):**
   ```
    "@wdio/cli": "^7.0.1",
    "@wdio/dot-reporter": "^7.0.1",
    "@wdio/junit-reporter": "^7.0.1",
    "@wdio/local-runner": "^7.0.1",
    "@wdio/mocha-framework": "^7.0.0",
    "@wdio/sauce-service": "^7.0.1",
    "@wdio/spec-reporter": "^7.0.1",
    "@wdio/sync": "^7.0.1",
   ```

**Config of WebdriverIO**
TSConfig:
```json
{
  "compilerOptions": {
    "target": "es2019",
    "lib": ["es2019"],
    "baseUrl": ".",
    "paths": {
      "*": ["./*"]
    },
    "esModuleInterop": true,
    "module": "commonjs",
    "isolatedModules": false,
    "plugins": [],
    "types": [
      "node",
      "webdriverio/async",
      "@wdio/mocha-framework",
      "expect-webdriverio"
    ]
  },
  "include": ["/**/*.js", "/**/*.ts"]
}
```

**Describe the bug**
After upgrading all Webdriver-related packages from 5.1.x to 7.0.x, my basic sample tests are failing. I'm using Typescript and async mode. First, I'm getting an Typescript error saying using `await $(...)` is not-thenable. Then, my tests are failing with it being unable to access `getAttribute()` of an element:

**To Reproduce**
```
  it('should find an element on the page', async () => {
    await browser.url('https://www.yahoo.com');

    const headerLogo = await $('#ybar-logo');
    const headerLogoHREF = headerLogo.getAttribute('href');
    expect(headerLogoHREF).toBe('https://www.yahoo.com/');
  });
```

The `const headerLogo = await $('#ybar-logo');` line returns:

```
Unexpected `await` of a non-Promise (non-"Thenable") value. eslint(@typescript-eslint/await-thenable)
```

And when I try to run this test, I get:

```
[0-0] RUNNING in chrome - /specs/sample-test.test.ts
[0-0] TypeError in "Yahoo should find an element on the page"
TypeError: headerLogo.getAttribute is not a function
    at Context.<anonymous> (/Users/denchen/git/ui/test/e2e/specs/sample-test.test.ts:20:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Context.executeAsync (/Users/denchen/git/ui/node_modules/@wdio/utils/build/shim.js:137:16)
    at Context.exports.testFrameworkFnWrapper (/Users/denchen/git/ui/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:51:18)
```

Again, this test worked fine on the prior version of Webdriver. I looked through the release notes and don't see anything else that I need to update in terms of configuration besides the TSConfig which I've copy & pasted above.

**Comment by christian-bromann** [comment]
Not sure but there seems to be a missing link in your upgrade. I just created a fresh project. Added 

```json
    "types": ["node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio"],
```

to my types and used your example with a little fix:

```suggestion
  it('should find an element on the page', async () => {
    await browser.url('https://www.yahoo.com');

    const headerLogo = await $('#ybar-logo');
-   const headerLogoHREF = headerLogo.getAttribute('href');
+   const headerLogoHREF = await headerLogo.getAttribute('href');
    expect(headerLogoHREF).toBe('https://www.yahoo.com/');
  });
```

and it worked for me.

**Comment by denchen** [comment]
@christian-bromann Ah, your small change worked for me. Although in the prior version of Webdriver, the original code worked for me instead.

I'm still getting a Typescript error about "Unexpected await of a non-Promise" for `await $('#ybar-logo');`. The error comes from `@typescript-eslint/await-thenable`, but obviously `$()` is a Promise. So I'm not sure what I need to configure to get Typescript to accept that fact.

**Comment by christian-bromann** [comment]
> but obviously `$()` is a Promise

Make sure you have [TypeScript configured](https://webdriver.io/docs/typescript) correctly. I will close because I think this is a setup issue. Happy to assist with further questions.
