### ISSUE TITLE
How can we use Visual regression service with Webdriver 5

### ISSUE THREAD

**Issue by aish-blr** [webdriverio/webdriverio#3851]
With Webdriver 5 and  wdio Visual regression service 0.9.0 installed, I am unable to use browser.checkElement(selector) function. I get to see the error "browser.checkElement is not a function"

I understand the wdio Visual regression service works with only Webdriver 4.8 only. 
Since i am using V5 I cannot now downgrade to 4.8...Is there a way to get to get some specific dependencies installed without impacting rest of the automation using V5

Since ApplitTools service is a paid tool, I am not interested in using that with V5

**Comment by wswebcreation** [comment]
Hi @aish-blr 

The wdio Visual regression service is not a WebdriverIO maintained module. We are also not going to port it to V5, please contact the maintainer of the project or maybe try to port it yourself to V5.
