### ISSUE TITLE
wdio/local-runner 6.12.0 typescript compilation error

### ISSUE THREAD

**Issue by snixer724** [webdriverio/webdriverio#6316]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.12.0
 - **Mode:** Test runner I think
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.16.2
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 87
 - **Platform name and version:** Mac
 - **Additional wdio packages used (if applicable):** spec reporter, selenium standalone

**Describe the bug**
When upgrading the wdio/local-runner to 6.11.0 or 6.12.0 I am receiving the following typescript error on runs.
`error TS2322: Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.`

It starts with this error: 
`ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.`

and then moves to the typescript error. However I believe that the browser error isn't the issue. When I downgrade back to 6.10.4 the issue is resolved.

**To Reproduce**
Setup a project with 
"@wdio/cli": "^6.12.0",
    "@wdio/local-runner": "^6.12.0",
    "@wdio/mocha-framework": "^6.11.0",
    "@wdio/selenium-standalone-service": "^6.4.0",
    "@wdio/spec-reporter": "^6.4.0",
    
and run a test. To fix downgrade @wdio/local-runner to 6.10.4

**Expected behavior**
Typescript error to not happen.

**Additional context**
I don't have a crazy setup going on and things were working fine before. The simple downgrade does work again. Has anyone else seen this?

**Comment by christian-bromann** [comment]
@snixer724 can you try to remove your `package-lock.json` and ensure that all wdio pasckages are on latest, then re-install the dependencies?

**Comment by snixer724** [comment]
@christian-bromann same issue. I believed I tried that before, but I just tried it again. Same typescript compilation error.

**Comment by paul-gladoon** [comment]
@christian-bromann I can confirm that I also have a problem when compiling, only of a different type:

Error: TSError: ⨯ Unable to compile TypeScript:
page_objects/index.ts(8,7): error TS2451: Cannot redeclare block-scoped variable 'lib_1'.

**Comment by ipopa** [comment]
I also have the same problem (`import { isEqual } from 'lodash';`)

`[0-0] (node:97561) UnhandledPromiseRejectionWarning: TSError: ⨯ Unable to compile TypeScript:
***.ts(4,7): error TS2451: Cannot redeclare block-scoped variable 'lodash_1'.`

    at createTSError (/****/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/****/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/****/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/****/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/****/node_modules/ts-node/src/index.ts:1043:43)
    at Module.m._compile (/****/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions.<computed> (/****/node_modules/ts-node/src/index.ts:1046:12)
    at Object.require.extensions.<computed> [as .ts] (/****/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by bablyukh** [comment]
I have the same issue: Cannot redeclare block-scoped variable

**Comment by ipopa** [comment]
I found the solution for my project (jasmine framework)
I changed 
```
  jasmineNodeOpts: {
    requires: ['ts-node/register', 'tsconfig-paths/register'],
  },
  ```
  to
  ```
  jasmineNodeOpts: {
    requires: ['tsconfig-paths/register'],
  },
  ```

**Comment by karfau** [comment]
I can confirm that dropping `'ts-node/register'` from the `mochaOpts.requires` list, or in my case dropping the whole key, resolved the issue.

**Comment by christian-bromann** [comment]
I added a commit to improve our release docs around this. Sorry for this confusion!
