### ISSUE TITLE
[🐛 Bug]: Jasmine typing issues

### ISSUE THREAD

**Issue by DirkoOdendaal** [webdriverio/webdriverio#14475]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.12.7

### Node.js Version

22.11.0 and 20.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript

```

### What happened?

This first `describe` in a spec file has a TS violation with the error:

`Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try 'npm i --save-dev @types/jest' or 'npm i --save-dev @types/mocha' and then add 'jest' or 'mocha' to the types field in your tsconfig.ts(2593)`

We've been getting this since upgrading to v8, but could get around it with adding @types/jasmine and adding jasmine to the typings for the spec files. This does cause some other knock on issues, but we could live with that for a while.
Now with wanting to upgrade to latest v9 from v8, we want to get this solved and have less issues.

Not sure if this might be environment specific or not.

### What is your expected behavior?

Any typings related to webdriverio and the jasmine framework it supports, need to resolve correctly and be reliable.

### How to reproduce the bug.

To reproduce this, you can look at the jasmine-boilerplate project.
https://github.com/webdriverio/jasmine-boilerplate

Install the node_modules with `npm install` and then have a look at the spec files in the test directory.

### Relevant log output

```typescript
Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig. (ts 2593)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by Kauanldsbarbosa** [comment]
try:

1. **Install Jasmine type definitions**:

```bash
npm install --save-dev @types/jasmine
````

2. **Add Jasmine to `tsconfig.json`**:

In the `tsconfig.json` file, add `"jasmine"` to the `"types"` section:

```json
{
"compilerOptions": {
"types": ["jasmine"]
}
}
```

3. **Check `wdio.conf.js`**:

Make sure the framework is set to `jasmine`:

```javascript
framework: 'jasmine',
```

4. **Run the Tests**:

Run the tests with:

```bash
npx wdio run wdio.conf.js
```

## If Persists

Remove conflicting dependencies such as `@types/jest` or `@types/mocha`:

```bash
npm uninstall @types/jest @types/mocha
```

These steps should resolve the typing error in Jasmine.

**Comment by DirkoOdendaal** [comment]
Hi @Kauanldsbarbosa ,

For some reason this feels like a AI generated response as it does not seem like the whole context was taken into account.

The WebdriverIO documentation does not say anything about adding the `@types/jasmine` typing, as I understand this is all provided through the `@wdio/jasmine-framework` typing.
https://webdriver.io/docs/typescript/#framework-types

`{
    "compilerOptions": {
        "types": ["node", "@wdio/globals/types", "@wdio/jasmine-framework"]
    }
}`

And as stated, we used to do that, but it does come with tradeoffs, which I believe is not what is meant to happen.
Also, the sample project I shared as none of the conflict dependencies you mentioned. I also believe that mature projects have a lot of other tests configured, relying on for example `@types/jest`, which does not make that a good solution IMO.

**Comment by Kauanldsbarbosa** [comment]
hi, @DirkoOdendaal 

I tried to leave the issue response in an organized way. I tried it in my environment and these are the logs from my test.

````
chrome 136.0.7103.92 linux #0-0] Running: chrome (v136.0.7103.92) on linux
[chrome 136.0.7103.92 linux #0-0] Session ID: 514196763ed336ee46ef698b6c71be5e
[chrome 136.0.7103.92 linux #0-0]
[chrome 136.0.7103.92 linux #0-0] » /test/specs/checkbox.spec.ts
[chrome 136.0.7103.92 linux #0-0] checkboxes
[chrome 136.0.7103.92 linux #0-0]    ✓ checkbox 2 should be enabled
[chrome 136.0.7103.92 linux #0-0]    ✓ checkbox 1 should be enabled after clicking on it
[chrome 136.0.7103.92 linux #0-0]
[chrome 136.0.7103.92 linux #0-0] 2 passing (3.8s)
------------------------------------------------------------------
[chrome 136.0.7103.92 linux #0-3] Running: chrome (v136.0.7103.92) on linux
[chrome 136.0.7103.92 linux #0-3] Session ID: 20dc847087d09fea78d1ec62758cab43
[chrome 136.0.7103.92 linux #0-3]
[chrome 136.0.7103.92 linux #0-3] » /test/specs/test.e2e.ts
[chrome 136.0.7103.92 linux #0-3] My Login application
[chrome 136.0.7103.92 linux #0-3]    ✓ should login with valid credentials
[chrome 136.0.7103.92 linux #0-3]
[chrome 136.0.7103.92 linux #0-3] 1 passing (4.3s)
------------------------------------------------------------------
[chrome 136.0.7103.92 linux #0-2] Running: chrome (v136.0.7103.92) on linux
[chrome 136.0.7103.92 linux #0-2] Session ID: a33423bad7dd1af68e4c7aa7c2c74c79
[chrome 136.0.7103.92 linux #0-2]
[chrome 136.0.7103.92 linux #0-2] » /test/specs/form.spec.ts
[chrome 136.0.7103.92 linux #0-2] auth form
[chrome 136.0.7103.92 linux #0-2]    ✓ should deny access with wrong creds
[chrome 136.0.7103.92 linux #0-2]    ✓ should allow access with correct creds
[chrome 136.0.7103.92 linux #0-2]
[chrome 136.0.7103.92 linux #0-2] 2 passing (5.8s)
------------------------------------------------------------------
[chrome 136.0.7103.92 linux #0-1] Running: chrome (v136.0.7103.92) on linux
[chrome 136.0.7103.92 linux #0-1] Session ID: f00cd0f63024bb2dbb7fa2fe2a33d376
[chrome 136.0.7103.92 linux #0-1]
[chrome 136.0.7103.92 linux #0-1] » /test/specs/dynamic.spec.ts
[chrome 136.0.7103.92 linux #0-1] dynamic loading
[chrome 136.0.7103.92 linux #0-1]    ✓ should be an button on the page
[chrome 136.0.7103.92 linux #0-1]
[chrome 136.0.7103.92 linux #0-1] 1 passing (7.3s)


Spec Files:      4 passed, 4 total (100% completed) in 00:00:14  

2025-05-13T18:03:19.639Z INFO @wdio/local-runner: Shutting down spawned worker
2025-05-13T18:03:19.895Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2025-05-13T18:03:19.895Z INFO @wdio/local-runner: shutting down
2025-05-13T18:03:19.896Z INFO @wdio/cli:launcher: Run onComplete hook
```

I'm sorry if it doesn't solve your situation

**Comment by DirkoOdendaal** [comment]
Hi @Kauanldsbarbosa 

No problem, some of the suggestions just did not align with what I explained.

But my problem is not with executing the tests, that works, but working with Typescript we use the best practice of checking for any TS violations. That is where my issue lies, whcih you can see from the bug report.

From the docs on the website that is also recommended:
https://webdriver.io/docs/typescript/#compile--lint

So, in the boilerplate example, if you run `npx tsx test/specs/checkbox.spec.ts`, do you get any errors?
This is what I get, which is the same as the IDE error I shared:


```
npx tsx test/specs/checkbox.spec.ts
npm warn Unknown user config "--init-author-name". This will stop working in the next major version of npm.
/Users/dirkoodendaal/Desktop/Repos/Personal/jasmine-boilerplate/test/specs/checkbox.spec.ts:3
describe('checkboxes', () => {
^


ReferenceError: describe is not defined
    at <anonymous> (/jasmine-boilerplate/test/specs/checkbox.spec.ts:3:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0
```

**Comment by Kauanldsbarbosa** [comment]
> Hi [@Kauanldsbarbosa](https://github.com/Kauanldsbarbosa)
> 
> No problem, some of the suggestions just did not align with what I explained.
> 
> But my problem is not with executing the tests, that works, but working with Typescript we use the best practice of checking for any TS violations. That is where my issue lies, whcih you can see from the bug report.
> 
> From the docs on the website that is also recommended: https://webdriver.io/docs/typescript/#compile--lint
> 
> So, in the boilerplate example, if you run `npx tsx test/specs/checkbox.spec.ts`, do you get any errors? This is what I get, which is the same as the IDE error I shared:
> 
> ```
> npx tsx test/specs/checkbox.spec.ts
> npm warn Unknown user config "--init-author-name". This will stop working in the next major version of npm.
> /jasmine-boilerplate/test/specs/checkbox.spec.ts:3
> describe('checkboxes', () => {
> ^
> 
> 
> ReferenceError: describe is not defined
>     at <anonymous> (/jasmine-boilerplate/test/specs/checkbox.spec.ts:3:1)
>     at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
>     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
>     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
> 
> Node.js v22.11.0
> ```

This way, it runs the test directly, with Jasmine not loaded, so Node doesn't know what describe is. I believe that's it. This way, mine also gave an error.

**Comment by DirkoOdendaal** [comment]
But that is exactly what `@wdio/jasmine-framework` together with `@wdio\types` is meant for. It's meant to supply the correct typings, which should allow this to pass.

This is not Node that has the issue, this is a Typing issue in WebdriverIO, hence the bug report.
If you have the same error and the docs say you should compile the code and it should pass with the recommended setup, then surely this is something to be fixed here?

**Comment by christian-bromann** [comment]
A workaround is to add this:
```ts
/// <reference types="jasmine" />
import { expect } from '@wdio/globals'
```

This indeed seems like a bug and an issue with how we propagate the Jasmine types in the framework adapter. Any contributions are welcome. I can't change the labels at the moment as there seems to be a `z-index` issue with the Github UI atm.

**Comment by DirkoOdendaal** [comment]
Thanks @christian-bromann ,
The workaround does work.

We're busy preparing for a big migration, so I'll try jump into this once I'm done.
I've spoken to @erwinheitzman about this a while ago, but I just forgot to create the bug.

**Comment by erwinheitzman** [comment]
I can have a look what changed in the adapter that could have caused this and attempt to fix it 👍

**Comment by mccmrunal** [comment]
@DirkoOdendaal   I looked into the issue its still replicable

@types/jasmine is in devDependencies instead of dependencies in @wdio/jasmine-framework. This means when users install the package, they don't get Jasmine type definitions. Compare with @wdio/mocha-framework where @types/mocha is correctly in dependencies.

https://github.com/webdriverio/webdriverio/pull/15001

**Comment by dprevost-LMI** [comment]
Hey!
I thought I cracked the case of Jasmine typing core problem vs expect global; however, seeing this issue fixed now, I wonder.
If anyone would like to take a peek at https://github.com/webdriverio/expect-webdriverio/issues/1893#issuecomment-3831094812 and rectify me if needed.
Thanks!
