### ISSUE TITLE
[@wdio/sync] [webdriverio-core.d.ts ] missing interface Browser extends WebDriver.BaseClient 

### ISSUE THREAD

**Issue by krishna01012002** [webdriverio/webdriverio#5490]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 6.1.17
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync , @wdio/sync
 - **Node.js version:** [v10.21.0]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [MAC OS Mojave 10.14.4]

**Config of WebdriverIO**
tsconfig.json
"types": ["node", "@wdio/sync", "mocha"],

**Describe the bug**
Seeing below issue after updating webdriverio6.015 to 6.1.17 and @wdio/sync 6.1.14

```
node_modules/@wdio/sync/webdriverio-core.d.ts:829:41 - error TS2694: Namespace 'WebDriver' has no exported member 'BaseClient'.

829     interface Browser extends WebDriver.BaseClient {
                                            ~~~~~~~~~~
```

**To Reproduce**
Update webdriverio package to 6.1.17

Update @wdio/sync package to 6.1.14
[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**

webdriverio-core.d.ts
```ts
  interface Browser extends WebDriver.BaseClient {
        config: Config;
        options: RemoteOptions;

        /**
         * add command to `browser` or `element` scope
         */
        addCommand(
            name: string,
            func: Function,
            attachToElement?: boolean
        ): void;

        /**
         * overwrite `browser` or `element` command
         */
        overwriteCommand(
            name: string,
            func: (origCommand: Function, ...args: any[]) => any,
            attachToElement?: boolean
        ): void;

```
========

webdriverio.d.ts
```ts
/// <reference types="@wdio/sync/webdriverio-core"/>

declare namespace WebdriverIO {
    interface Browser {
        /**
         * execute any async action within your test spec
         */
        call: <T>(callback: (...args: any[]) => Promise<T>) => T;

        /**
         * Inject a snippet of JavaScript into the page for execution in the context of the currently selected frame.
         * The executed script is assumed to be synchronous and the result of evaluating the script is returned to
         * the client.
         */
        execute: <T>(script: string | ((...arguments: any[]) => T), ...arguments: any[]) => T;

        // also there is no way to add callback as last parameter after `...args`.
        // https://github.com/Microsoft/TypeScript/issues/1360
        // executeAsync: <T>(script: string | ((...arguments: any[], callback: (result: T) => void) => void), ...arguments: any[]) => T;
        /**
         * Inject a snippet of JavaScript into the page for execution in the context of the currently selected frame.
         * The executed script is assumed to be asynchronous and must signal that is done by invoking
         * the provided callback, which is always provided as the final argument to the function. The value
         * to this callback will be returned to the client.
         */
        executeAsync: (script: string | ((...arguments: any[]) => void), ...arguments: any[]) => any;
    }

    interface BrowserObject extends WebDriver.ClientOptions, WebDriver.Client, WebdriverIO.Browser { }
}

declare var browser: WebdriverIO.BrowserObject;
declare var driver: WebdriverIO.BrowserObject;

/**
 * find a single element on the page.
 */
declare function $(selector: string | Function): WebdriverIO.Element;

/**
 * find multiple elements on the page.
 */
declare function $$(selector: string | Function): WebdriverIO.ElementArray;

declare module "@wdio/sync" {
    export = WebdriverIO
}
```

**Additional context**
Looks like webdriverio.d.ts missing namespace BaseClient

> Please use the correct markdown

**Comment by krishna01012002** [comment]
Any update?

**Comment by christian-bromann** [comment]
> Any update?

Feel free to provide a PR with a fix.

**Comment by christian-bromann** [comment]
@krishna01012002 it would be great if you could provide a minimal reproducible project example where this typescript error comes up.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
