### ISSUE TITLE
waitForExist() throws error, when an element is not found on the page

### ISSUE THREAD

**Issue by aniruddhasahu** [webdriverio/webdriverio#774]
In webdriverio v3.2.0:
while calling, waitForExist('#someId', 6000); it throws error : 
" undefined: element ('#someId') still not existing after 6000 ms ".
and skips to later promises. As it is working fine with prior version (v3.1.0)

**Comment by christian-bromann** [comment]
@aniruddhasahu `waitForExist` is suppose to throw an error and stop the queue. We improved WebdriverIOs error handling in v3.2.0.

**Comment by aniruddhasahu** [comment]
Okay, I was using a month older version and just updated yesterday.
As I mention in prior version if an element is found then in the callback function of promise [.then(function(result){})]  the 'result' becomes 'true' otherwise 'undefined'.
So in order to test whether an element is present or not on the page, what should I do?  

Again thanks for the clarification.

**Comment by christian-bromann** [comment]
@aniruddhasahu just use waitForExist:

```js
browser.waitForExist('#someElem', 5000)
```

If the element doesn't show up until the timeout is reached the command will throw an error and your test should fail.

**Comment by jbrody17** [comment]
@aniruddhasahu if you want to just test whether or not an element is present on the page, but not error out if the element is not present, you can define a function like

            if(browser.isExisting(selector))
            {
              return true;
            }
            else return false;

**Comment by osmolyar** [comment]
@aniruddhasahu if you want to just test whether or not an element is present on the page, but not error out if the element is not present, you can define a function like

        if(browser.isExisting(selector))
        {
          return true;
        }
        else return false;
