### ISSUE TITLE
[🐛 Bug]: TypeError: socketUrl.replace is not a function after upgrade to v9

### ISSUE THREAD

**Issue by mykola-mokhnach** [webdriverio/webdriverio#13415]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.04

### Node.js Version

LTS

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  capabilities: {
    alwaysMatch: {
      browserName: 'MozillaFirefox',
      platformName: 'linux',
      'appium:automationName': 'Gecko',
      webSocketUrl: true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MozillaFirefox',
    platformName: 'linux',
    'appium:automationName': 'Gecko',
    webSocketUrl: true
  }
}
```
```


### What happened?

Trying to initialise mobile geckodriver session using above capabilities fails with the following exception after upgrade to v9.0.4:

```
1) Desktop Gecko Driver
       "before each" hook for "should start and stop a session":
     TypeError: socketUrl.replace is not a function
      at initiateBidi (file:///home/runner/work/appium-geckodriver/appium-geckodriver/node_modules/webdriver/build/index.js:1104:25)
      at Function.newSession (file:///home/runner/work/appium-geckodriver/appium-geckodriver/node_modules/webdriver/build/index.js:1512:36)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async remote (file:///home/runner/work/appium-geckodriver/appium-geckodriver/node_modules/webdriverio/build/index.js:6964:20)
      at async Context.<anonymous> (test/functional/desktop-driver-e2e-specs.js:26:14)
```

https://github.com/appium/appium-geckodriver/actions/runs/10452627737/job/28942898563

There is no such exception if WDIO v8 is used.

### What is your expected behavior?

The session should start properly

### How to reproduce the bug.

https://github.com/appium/appium-geckodriver/pull/120

### Relevant log output

```typescript
https://github.com/appium/appium-geckodriver/actions/runs/10452627737/job/28942898563?pr=120
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@mykola-mokhnach it seems like Appium returns the `webSocketUrl` capability as boolean value. I am not entirely sure if the WebDriver spec defines this but Appium should strip out the `webSocketUrl` capability if it doesn't support Bidi. Anyway, I will push a patch with a fix.

**Comment by mykola-mokhnach** [comment]
Thanks for checking it @christian-bromann 

@jlipps could you please take a look at the server implementation regarding the above comment?
