### ISSUE TITLE
wdio@7.9.0: elem[prop] is not a function

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#7229]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.0
 - **Mode:** Standalone mode
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** Linux

**Describe the bug**
When I update wdio to 7.9.0 I faced with error: 
```
TypeError: elem[prop] is not a function
    at /Users/dudkevich/job/projects/dudkevich-scripts/FEI-23192.wdio_7.9.0/node_modules/@wdio/utils/build/shim.js:197:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-23192.wdio_7.9.0/node_modules/@wdio/utils/build/shim.js:103:29)
```

After some debugging I found a minimal case:
```
const {remote} = require('webdriverio')

let browser;

const opts = {
    automationProtocol: 'devtools',
    capabilities: {
        browserName: 'chrome'
    }
};

(async function () {
    browser = await remote(opts);

    browser.overwriteCommand('$', (origFn, ...args) => {
        return origFn(...args).finally(() => {
            console.log('AFTER CALL $');
        });
    });

    await browser.url('https://github.com');
    await browser.$('body')

    await browser.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await browser.deleteSession()
    });
```

The problem is here - `origFn(...args).finally(...)`. Why I can't do it anymore? Is it any workaround? Should I use async-await with try-catch-finally? It looks like that problem in new proxy object.

**Comment by christian-bromann** [comment]
Thanks for raising the issue. This should be fixed within the proxy definition. Any contributions are welcome.

**Comment by christian-bromann** [comment]
Fixed in #7291
