### ISSUE TITLE
multiremote is broken in 5.4.13

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3492]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.13

**Config of WebdriverIO**
```
    capabilities: {
        myChromeBrowser: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        myFirefoxBrowser: {
            capabilities: {
                browserName: 'firefox'
            }
        }
    }
```

**Describe the bug**
multiremote stopped working in 5.4.13 due to bug in isRDC

**To Reproduce**
launch multiremote session

**Expected behavior**
multiremote should work

**Log**
```
@wdio/config/build/lib/ConfigParser.js:84
      throw e;
      ^

TypeError: this._capabilities.some is not a function
    at ConfigParser.addConfigFile (/Users/mygr/sources/e2e/node_modules/@wdio/config/build/lib/ConfigParser.js:75:40)
```

**Additional context**
https://github.com/webdriverio/webdriverio/pull/3468
https://github.com/webdriverio/webdriverio/pull/3468/files#r253472523

**Comment by wswebcreation** [comment]
@xlenz 

Hmm, I see, for multiremote you need to provide an object instead of an array according to the docs. I'll try to make a fix for it

**Comment by christian-bromann** [comment]
we need a multiremote smoke test to prevent this from happening again
