### ISSUE TITLE
TS compiler returns "error TS2339: Property 'hex' does not exist on type 'ParsedColor'"

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6450]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.15.4
 - **NPM version:** 6.14.10
 - **TypeScript version:** 4.1.5
 - **Additional wdio packages used (if applicable):** "@wdio/allure-reporter", "@wdio/devtools-service", "@wdio/local-runner", "@wdio/mocha-framework", "@wdio/spec-reporter", "@wdio/sync", "@wdio/types"

**dependencies**
```
    "@types/chai": "^4.2.13",
    "@types/jquery": "^3.5.5",
    "@types/mocha": "^8.2.0",
    "@types/node": "^14.11.8",
    "@wdio/allure-reporter": "^7.0.4",
    "@wdio/cli": "^7.0.4",
    "@wdio/devtools-service": "^7.0.4",
    "@wdio/local-runner": "^7.0.4",
    "@wdio/mocha-framework": "^7.0.4",
    "@wdio/spec-reporter": "^7.0.4",
    "@wdio/sync": "^7.0.4",
    "@wdio/types": "^7.0.4",
    "allure-commandline": "^2.13.0",
    "aws-sdk": "^2.844.0",
    "browserstack-local": "^1.4.5",
    "chai": "^4.2.0",
    "chromedriver": "^88.0.0",
    "node-rest-client": "^3.1.0",
    "node-wget": "^0.4.3",
    "pg": "^8.2.1",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.1.5",
    "wdio-chromedriver-service": "^6.0.3",
    "wdio-json-reporter": "^2.0.0"
```

**tsconfig.json**
```
{
    "compilerOptions": {
        "paths": {
            "*": [ "./*" ],
            "src/*": ["./src/*"]
        },
        "outDir": "./build",
        "allowJs": true,
        "types": [
            "node",
            "webdriverio/sync",
            "@wdio/mocha-framework",
            "@wdio/devtools-service",
          ],
        "inlineSourceMap": true,
        "target" : "es2019",     
    }, 
}
```

**Describe the bug**
After the update of the WDIO to v7 and TS to v4 the compiler returns error. The code compiled and worked fine before the update of the dependencies. 
The same code on JS is working fine.

```
[0-0] 2021-02-16T10:22:47.895Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/denys.barkanov/SDET/aqa-www.reasonsecurity.com/test/specs/id.test.ts
Error: TSError: ⨯ Unable to compile TypeScript:
pageObjects/components/Header.ts(290,66): error TS2339: Property 'hex' does not exist on type 'ParsedColor'.
...
[0-0] RUNNING in chrome - /test/specs/id.test.ts
[0-0] 2021-02-16T10:22:49.418Z ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/denys.barkanov/SDET/aqa-www.reasonsecurity.com/test/specs/id.test.ts
Error: TSError: ⨯ Unable to compile TypeScript:
pageObjects/components/Header.ts(290,66): error TS2339: Property 'hex' does not exist on type 'ParsedColor'.
...
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/denys.barkanov/SDET/aqa-www.reasonsecurity.com/test/specs/id.test.ts
Error: TSError: ⨯ Unable to compile TypeScript:
pageObjects/components/Header.ts(290,66): error TS2339: Property 'hex' does not exist on type 'ParsedColor'.
```

**To Reproduce**
```
//@ts-ignore
colorTSIGNOR: this.signUpBtn.getCSSProperty('color').parsed.hex, //the line is closed for the compiler
colorASANY: (this.signUpBtn.getCSSProperty('color').parsed as any).hex, //the line can be compiled okay
colorHEX: this.signUpBtn.getCSSProperty('color').parsed.hex, // the line can not be compiled by the TS compiler
```

![Screen Shot 2021-02-16 at 12 47 47 PM](https://user-images.githubusercontent.com/45456152/108052701-2fb73900-7055-11eb-83b0-c931bf9dcdc1.png)

![Screen Shot 2021-02-16 at 12 48 22 PM](https://user-images.githubusercontent.com/45456152/108052770-43629f80-7055-11eb-8248-c140e30aaa3b.png)

![Screen Shot 2021-02-16 at 12 48 36 PM](https://user-images.githubusercontent.com/45456152/108052801-4b224400-7055-11eb-97cb-1a01f407a5f2.png)

**Expected behavior**
The dependencies update is not crushed all the project flow.

**Comment by dannyfink** [comment]
Included a fix in https://github.com/webdriverio/webdriverio/pull/6498

**Comment by christian-bromann** [comment]
Thanks @dannyfink for the quick fix!
