### ISSUE TITLE
browser.setViewportSize no longer works after upgrade to v5

### ISSUE THREAD

**Issue by xkizer** [webdriverio/webdriverio#3405]
After upgrading to version 5 (specifically npm version 5.3.5), `browser.setViewportSize` fails (`browser.setViewportSize is not a function`). I have looked at the changelog and can't find any mention of `setViewportSize`. This worked fine in version 4.

**Comment by christian-bromann** [comment]
This command doesn't exist anymore, please use [setwindowrect](https://webdriver.io/docs/api/webdriver.html#setwindowrect).

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by livemixlove** [comment]
My two cents here is that we should be encouraging people to use stackoverflow, not gitter.  I quickly get frustrated with overlapping conversations on the gitter account.

**Comment by vimalmishra12** [comment]
@christian-bromann I want to set the size of my viewport. Correct me if i am wrong but "setwindowrect" works in the same way as [setWindowSize](https://webdriver.io/docs/api/browser/setWindowSize.html). What I want is to set dimensions of the viewport.

**Comment by christian-bromann** [comment]
> What I want is to set dimensions of the viewport.

What is the difference?

**Comment by ivanixgames** [comment]
@christian-bromann  
Setting windows size instead of viewport size can matter when doing image comparison of screen shots since browser and window managers affect the window border.

**Comment by ivanixgames** [comment]
For future seekers, here's a similar replacement for setViewPort:
`browser.addCommand('setViewPort', function (width, height, x, y) {
    const diff = browser.execute('return ({width: window.outerWidth - window.innerWidth, height: window.outerHeight - window.innerHeight});');
    const vw = width - diff.width;
    const vh = height - diff.height;
    browser.setWindowRect(x || 0, y || 0, vw, vh);   
});
`

**Comment by olegKusov** [comment]
where is your changelogs, guys? Why we need to create issue to find out that this command is no longer exist

**Comment by zbyte64** [comment]
I have forgotten how to search. I can't find mention of it in the change logs 😵‍💫
