### ISSUE TITLE
(0 , _webdriver.webdriverMonad) is not a function

### ISSUE THREAD

**Issue by kellyselden** [webdriverio/webdriverio#4505]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.6
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.16.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** Mac OSX

**Config of WebdriverIO**
`const { remote } = require('webdriverio');`

**Describe the bug**
It appears a recent release has regressed. Do to transitive dependencies, the error started showing up in our logs today.

**To Reproduce**

https://github.com/CrowdStrike/faltest/pull/34

**Log**

https://travis-ci.org/CrowdStrike/faltest/jobs/586009664#L4265

```
TypeError: (0 , _webdriver.webdriverMonad) is not a function
      at Browser.findElement (node_modules/webdriverio/build/utils/getElementObject.js:33:49)
      at Browser.$ (node_modules/webdriverio/build/commands/browser/$.js:56:39)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by mgrybyk** [comment]
Most likely you have some issue with node modules.
webdriverMonad has been moved to @wdio/utils

Feel free to reopen if it's still an issue

**Comment by christian-bromann** [comment]
Please make sure to update all packages to use the latest version.

**Comment by christian-bromann** [comment]
You need to update https://github.com/CrowdStrike/faltest/blob/master/packages/remote/package.json#L40

**Comment by kellyselden** [comment]
That shouldn't be necessary if they are in SemVer range. Is this a breaking change?

**Comment by christian-bromann** [comment]
> Is this a breaking change?

You can't just update the packages in package-lock and don't include other packages as well. If you update the version in the package.json then this bug wouldn't have appeared.

**Comment by kellyselden** [comment]
That's how SemVer works. You should be pinning all of your inter-dependencies if they don't work together on different versions.

If `webdriverio@5.11.6` doesn't work with `webdriver@5.13.0` (and `@wdio/utils@5.13.0`), then you shouldn't have a SemVer range of `webdriver "^5.11.5"` that says it does.

```
webdriverio@5.11.6:
  version "5.11.6"
  dependencies:
    webdriver "^5.11.5"

webdriver@^5.11.5:
  version "5.13.0"
  dependencies:
    "@wdio/config" "^5.13.0-alpha.0"
    "@wdio/logger" "^5.12.1"
    "@wdio/protocols" "^5.13.0-alpha.0"
    "@wdio/utils" "^5.13.0"
```

A consumer shouldn't have to stay in lockstep with webdriverio to keep it working. A lockfile should be able to be regenerated without it breaking, regardless if they're pinned or not.

**Comment by christian-bromann** [comment]
> You should be pinning all of your inter-dependencies if they don't work together on different versions.

Fair enough, however if you would have updated the the version in package.json this error would not happen.

**Comment by kellyselden** [comment]
> however if you would have updated the the version in package.json this error would not happen

I think you may be missing the impact of this. My repo was unaffected because I have a lockfile. Consumers of my package started getting the error on new installs. I have certain packages pinned in my package.json for various reasons, mostly regression reasons like [this](https://github.com/webdriverio/webdriverio/pull/4360). In this case, I would have a release a new version of my package as soon as possible after your releases to assure it stays working.

Would you support a change to pin all your versions?

**Comment by christian-bromann** [comment]
> Would you support a change to pin all your versions?

Yes

**Comment by christian-bromann** [comment]
@kellyselden just made a release for all packages and versions are now pinned

**Comment by kellyselden** [comment]
@christian-bromann Thank you!
