### PR TITLE
Run tests on current NodeJS versions

### PR DESCRIPTION
**Pull request by alippai**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
I don't think this is a good idea. The tests already take a long time. Running these on other node versions would triple the time and is not really necessary imo.

**Comment by alippai** [comment]
I had an error after updating 4.9.8 to 4.9.9: `Something went wrong: TypeError: process.execArgv[i].match is not a function` so I wanted make sure webdriverio passes the tests _now_. I totally understand the reasons why won't you merge this change.

**Comment by christian-bromann** [comment]
@alippai this issue is unrelated to the node version

**Comment by christian-bromann** [comment]
@alippai how can we reproduce the error you were facing?

**Comment by alippai** [comment]
I'm not sure. Maybe it's grunt-webdriver?!
I'll try to get some details.

**Comment by christian-bromann** [comment]
@codiophile @alippai I don't know if there is a need to check params. I think the issue has a different origin.
