### ISSUE TITLE
[🐛 Bug]: Mocha unable to resolve local test spec on Windows. 

### ISSUE THREAD

**Issue by siggerzz** [webdriverio/webdriverio#8828]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

14.19.7

### Node.js Version

14.20.0 / 16.x

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 1,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [].concat(configuration.availableServices.chromedriver.headless ? [
                '--no-sandbox',
                '--disable-infobars',
                '--headless',
                '--disable-gpu',
                '--window-size=1920,1080'] : [])
        }
    }]
```

### What happened?

In this [UI monorepo](https://www.github.com/justeat/fozzie-components), we have a number of page objects for each of the contained UI components. These 'component objects' get exported as part of our published npm packages, so that WebDriverIO test frameworks in our consuming applications can use them to construct the larger page objects. An example of a large page object can be seen [here](https://gist.github.com/siggerzz/4bafd6267314a2e65aa02bc48797297b)

Recently, we refactored all WDIO code in the monorepo to be async, due to the[ Sync API being deprecated in Node 16](https://webdriver.io/blog/2021/07/28/sync-api-deprecation/)

As part of this change, we also refactored all of our component objects to use ES6 import syntax. An example of which can be seen [here ](https://github.com/justeat/fozzie-components/blob/wdio-bug-test/packages/components/atoms/f-wdio-test/test-utils/component-objects/f-wdio-test.component.js).

**Note**: We are importing to untranspiled files directly into our consuming application, as getting babel to transpile our page objects dramatically increases our bundlesize. I expect long-term, the best solution would be to transpile these as part of the published `@justeat` package, however I need to look more into bundle splitting.

**The problem**
Whilst the tests work fine in this repo, the import changes have caused tests to break in our consuming applications with the stack trace seen below, when an imported component object is referenced via node_modules.: (I'm unable to provide code to the consuming application, hence why I've created a reproducible demo in this repo)

I believe this is due to the fact that by default, Babel does not transpile anything inside of the node_modules.

To get around this, we added [the following code](https://github.com/justeat/fozzie-components/blob/wdio-bug-test/wdio-shared.conf.js#L1) in our consuming applications wdio.shared.conf.js, to ensure babel only transpiles packages that live as part of the @justeat namespace.

This seems to fix the issue when running on Mac, however we're still seeing the following error when running the tests on Windows machines:
```
Error: Error: Cannot find module 'file:///C:/code/fozzie-components/packages/components/atoms/f-wdio-test/test/component/f-wdio-test.component.spec.js'Require stack:
- C:/code/fozzie-components/node_modules\mocha\lib\nodejs\esm-utils.js
- C:/code/fozzie-components/node_modules\mocha\lib\mocha.js
- C:/code/fozzie-components/node_modules\mocha\index.js
- C:/code/fozzie-components/node_modules\@wdio\mocha-framework\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\utils.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\initialisePlugin.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\runner\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\local-runner\build\run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:7:14
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at formattedImport (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:7:14)
    at Object.exports.requireOrImport (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:48:32)
    at Object.exports.loadFilesAsync (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:103:20)
    at MochaAdapter._loadFiles (C:/code/fozzie-components/node_modules\@wdio\mocha-framework\build\/index.js:68:13)
```

We're unsure why we're seeing this issue given it's complaining about a local file, however I did notice the following issues in the WebDriverIO and Mocha repo, and wonder if they could be related:

https://github.com/webdriverio/webdriverio/issues/8689

https://github.com/mochajs/mocha/pull/4901

The files of interest are:

Test Spec where we import a component object via npm (Normally we import these into the consuming applications page object, but it was easier for me to reproduce like this in this repo) - https://github.com/justeat/fozzie-components/blob/wdio-bug-test/packages/components/atoms/f-wdio-test/test/component/f-wdio-test.component.spec.js#L2

The component object we're importing - https://github.com/justeat/fozzie-components/blob/wdio-bug-test/packages/components/atoms/f-button/test-utils/component-objects/f-button--action.component.js

It's also worth mentioning we've followed the [Babel Setup](https://webdriver.io/docs/babel/) without any luck.

### What is your expected behavior?

Component page objects imported via `node_modules` are transpiled / resolved by Babel, and tests continue to pass on windows.

### How to reproduce the bug.

Checkout the following branch and run the setup steps provided. - https://github.com/justeat/fozzie-components/pull/2123

### Relevant log output

```typescript
Console output in our consuming application with new ES6 component objects:


Spec file(s): /Users/ben.siggery/Code/fozzie-components/packages/components/atoms/f-wdio-test/test/component/f-wdio-test.component.spec.js
Error: /Users/ben.siggery/Code/fozzie-components/packages/components/atoms/f-button/test-utils/component-objects/f-button--action.component.js:1
import Page from '@justeat/f-wdio-utils';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Module._compile (/Users/ben.siggery/Code/fozzie-components/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/ben.siggery/Code/fozzie-components/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/ben.siggery/Code/fozzie-components/packages/components/atoms/f-wdio-test/test/component/f-wdio-test.component.spec.js:2:1)
```

The error seen on Windows machines when adding [the following code](https://github.com/justeat/fozzie-components/blob/wdio-bug-test/wdio-shared.conf.js#L1) in our consuming applications wdio.shared.conf.js, to ensure babel only transpiles packages that live as part of the @justeat namespace.

```
Error: Error: Cannot find module 'file:///C:/code/fozzie-components/packages/components/atoms/f-wdio-test/test/component/f-wdio-test.component.spec.js'Require stack:
- C:/code/fozzie-components/node_modules\mocha\lib\nodejs\esm-utils.js
- C:/code/fozzie-components/node_modules\mocha\lib\mocha.js
- C:/code/fozzie-components/node_modules\mocha\index.js
- C:/code/fozzie-components/node_modules\@wdio\mocha-framework\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\utils.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\initialisePlugin.js
- C:/code/fozzie-components/node_modules\@wdio\utils\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\runner\build\index.js
- C:/code/fozzie-components/node_modules\@wdio\local-runner\build\run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:7:14
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at formattedImport (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:7:14)
    at Object.exports.requireOrImport (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:48:32)
    at Object.exports.loadFilesAsync (C:/code/fozzie-components/node_modules\mocha\lib\nodejs\/esm-utils.js:103:20)
    at MochaAdapter._loadFiles (C:/code/fozzie-components/node_modules\@wdio\mocha-framework\build\/index.js:68:13)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by siggerzz** [comment]
I've just tested manually applying this fix to my branch, however I still seeing the same 'Cannot find module' issue - https://github.com/mochajs/mocha/pull/4901

**Comment by christian-bromann** [comment]
> I've just tested manually applying this fix to my branch

This fix has nothing to do with your issue.

I unfortunately don't have the time to look into your project but from what I saw at first glance is that you register babel way to many times which is not necessary as WebdriverIO does all that for you. I saw:

```ts
require('@babel/register')({ ignore: [/node_modules\/(?!(@justeat))/] });
```

at the beginning of [`wdio-shared.conf.js`](https://github.com/justeat/fozzie-components/pull/2123/files#diff-76d024ed2f74a5d1863b79ef57802ffade412c835ae03a78b8dfe32ad464d55a) and a 

```ts
require: ['@babel/register'],
```

in the mochaOpts config. This is all not necessary and also no where documented in the WebdriverIO docs. I recommend removing these entries. Another thing what you can try is to set up a new project with Mocha and Babel pre-setup and just copy over the settings from the new project.

**Comment by siggerzz** [comment]
Cheers @christian-bromann, will give this a try:

Also, looks like the `mochaOpts` reference was from some V6 code we forgot to move when we migrated to V7 👍🏼 
https://v6.webdriver.io/docs/babel.html

**Comment by christian-bromann** [comment]
@siggerzz let me know if I can close this.

**Comment by siggerzz** [comment]
I'm not sure why, but I managed to fix this issue by changing the following in my wdio.config.js:

`require('@babel/register')({ ignore: [/node_modules\/(?!@justeat)/] });`

to

`require('@babel/register')({ exclude: ['node_modules/@justeat/**/*.js'] });`
