### ISSUE TITLE
 driver.gridTestSession is not a function

### ISSUE THREAD

**Issue by hzk007** [webdriverio/webdriverio#7436]
**Environment (please complete the following information):**
 - **WebdriverIO version:7.12.5 [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:12.18.0 [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:93 [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Try with  driver.gridTestSession with selenium hub 4.0, but failed with this error : driver.gridTestSession is not a function, But works well with selenium hub 3.0. Does it not support in selenium 4.0?

**To Reproduce**

[Include code or an example repository that can easily be set up]
  const driver = await remote({
    hostname: myhub,
    port: 4444,
    path: '/wd/hub',
    capabilities: {
      browserName: 'chrome',
    },
  });
  let detatail = driver.gridTestSession(driver.sessionId);

**Expected behavior**
  hope to get detail result with correct sessionid

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Fixed in #7437
