### ISSUE TITLE
mocha retries doesn't work anymore in it scope

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#4863]
mocha retries in following code snippet work in the describe scope, but not in the it scope.

```
import { expect } from 'chai';

describe('Mocha Retries', function () {
  // Work
  this.retries(4);

  it('doesn\'t work in it', function () {
    this.retries(2);
    expect(true).to.be.false;
  });
});
```
Error message:
```
[0-0] TypeError in "Mocha Retries doesn't work in it"
this.retries is not a function

 "spec" Reporter:
------------------------------------------------------------------
[chrome  linux #0-0] Spec: /home/pascal/repos/webdriverio-common/test/specs/example/demo.ts
[chrome  linux #0-0] Running: chrome on linux
[chrome  linux #0-0] Session ID: 516bca6f087cf99756494f165c44f434
[chrome  linux #0-0]
[chrome  linux #0-0] Mocha Retries
[chrome  linux #0-0]    ? doesn't work in it
[chrome  linux #0-0]    ? doesn't work in it
[chrome  linux #0-0]    ? doesn't work in it
[chrome  linux #0-0]    ? doesn't work in it
[chrome  linux #0-0]    ✖ doesn't work in it
[chrome  linux #0-0]
[chrome  linux #0-0] 1 failing (3.4s)
[chrome  linux #0-0]
[chrome  linux #0-0] 1) Mocha Retries doesn't work in it
[chrome  linux #0-0] this.retries is not a function
[chrome  linux #0-0] TypeError: this.retries is not a function
[chrome  linux #0-0]     at Context.<anonymous> (/home/pascal/repos/webdriverio-common/test/specs/example/demo.ts:8:10)
```

this worked in @wdio/sync 5.16.11 but didn't work anymore in 5.16.14
I am using @wdio/sync with mocha, chai and typescript

**Comment by mgrybyk** [comment]
Thank you for submitting, this is known regression and gonna be fixed soon https://github.com/webdriverio/webdriverio/pull/4861

**Comment by pako88** [comment]
great to hear, thanks :)
