### ISSUE TITLE
Wait.Until() Hangs And Fails As Code Under Promise Is Never Executed At All

### ISSUE THREAD

**Issue by dheeraj1988** [webdriverio/webdriverio#1162]
Hey @christian-bromann ,

I am facing issue with webdriverio - "~3.4.0". I am using cucumber boilerplate with webdriverio. This is the code I have written -

module.exports = function (ms, elem, expectedText, done) { this.browser.waitUntil(function() { return this.getText(element).then(function(text) { return text.indexOf(expectedText) >= 0; }); }, ms) .call(done); };

Issue -

Uncaught Error: Promise never resolved with an truthy value
     at new ErrorHandler.CommandError (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\utils\ErrorHandler.js:87:12)
     at reject (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\commands\waitUntil.js:41:18)
     at Object.waitUntilPrivate (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\commands\waitUntil.js:62:9)
     at Object.safeExecute (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\utils\safeExecute.js:19:24)
     at Object.WebdriverIO.resolve (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\webdriverio.js:87:29)
     at C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\lib\webdriverio.js:225:32
     at _fulfilled (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:820:54)
     at self.promiseDispatch.done (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:849:30)
     at Promise.promise.promiseDispatch (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:782:13)
     at C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:590:44
     at runSingle (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:123:13)
     at flush (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\q\q.js:111:13)

**Comment by christian-bromann** [comment]
@dheeraj1988 this is not an error, the condition within your waitFor command hasn't been met and still returns false after the timeout.

**Comment by dheeraj1988** [comment]
@christian-bromann : I dont think timeout ever comes into picture. I tried the following code and it straight away fails.

`    this.browser.waitUntil(function() {
      return this.getText(element).then(function(text) {
          console.log(text);
        return false;
      });
     }, ms, 1000)
    .call(done);
};`

**Comment by ishristov** [comment]
The promise never resolves for me either (actually the code in the promise is not executed at all).

```
client.waitUntil(function () {
  return this.getValue('#button').then(function (value){
    console.log('this is never executed')
    return true
  })
})
```
This hangs.

```
client.getValue('#button').then(function (value){
  // this is shown in the terminal
  console.log(value)
})
```

**Comment by dheeraj1988** [comment]
Yeah I have updated my webdriverio version to 4.0.3 and I am facing the same thing. The code in promise is never resolved at all with the following error -

Uncaught TypeError: this.getText is not a function

**Comment by christian-bromann** [comment]
Yeah there was actually a bug with the scope and was fixed by #1165. Will update the version later today. Should work with v4.0.4

**Comment by dheeraj1988** [comment]
@christian-bromann  : webdriverio still doesnt wait until the promise returns true and fails straight away but now the condition is checked atleast.
