### ISSUE TITLE
[🐛 Bug]: Typescript@4 errors in getProperty.d.ts

### ISSUE THREAD

**Issue by PaulKiddle** [webdriverio/webdriverio#10280]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.8 & latest

### Node.js Version

16.19.0

### Mode

Standalone Mode

### What happened?

Using typecript@4 (I couldn't find any notes about what versions of typescript are supported, but I would only expect support for a given ts version to be dropped on major releases)

Running `tsc` on our codebase since upgrading from 8.6.7 to 8.6.8 produces a series of compiler errors in `node_modules/webdriverio/build/commands/element/getProperty.d.ts`:

 - `Cannot find name 'CheckVisibilityOptions'.` on line 23
 - `Cannot find name 'MathMLElementTagNameMap'` in 8 different locations

### What is your expected behavior?

TSC succeeds without compile errors

### How to reproduce the bug.

Create a project with the following deps:

```json
  "devDependencies": {
    "@types/debug": "^4.1.7",
    "typescript": "^4.9.5",
    "webdriverio": "^8.8.7"
  }
```

Create a file called `test.ts`

```typescript
import 'webdriverio';
```

Create a file called `tsconfig.json`

```json
{
	"compilerOptions": {
	  "moduleResolution": "node",
	  "esModuleInterop": true,
	  "target": "ESNext",
	},
	"include": ["test.ts"]
  }
  ```

run `npx tsc`

### Relevant log output

```typescript
node_modules/webdriverio/build/commands/element/getProperty.d.ts:23:188 - error TS2304: Cannot find name 'CheckVisibilityOptions'.

23 } | NamedNodeMap | DOMTokenList | ((this: Element, ev: Event) => any) | ((this: Element, ev: Event) => any) | Document | ShadowRoot | ((init: ShadowRootInit) => ShadowRoot) | ((options?: CheckVisibilityOptions | undefined) => boolean) | {
                                                                                                                                                                                              ~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:26:24 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

26     <K_4 extends keyof MathMLElementTagNameMap>(selector: K_4): MathMLElementTagNameMap[K_4] | null;
                          ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:26:65 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

26     <K_4 extends keyof MathMLElementTagNameMap>(selector: K_4): MathMLElementTagNameMap[K_4] | null;
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:31:24 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

31     <K_7 extends keyof MathMLElementTagNameMap>(qualifiedName: K_7): HTMLCollectionOf<MathMLElementTagNameMap[K_7]>;
                          ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:31:87 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

31     <K_7 extends keyof MathMLElementTagNameMap>(qualifiedName: K_7): HTMLCollectionOf<MathMLElementTagNameMap[K_7]>;
                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:51:25 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

51     <K_11 extends keyof MathMLElementTagNameMap>(selectors: K_11): MathMLElementTagNameMap[K_11] | null;
                           ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:51:68 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

51     <K_11 extends keyof MathMLElementTagNameMap>(selectors: K_11): MathMLElementTagNameMap[K_11] | null;
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:57:25 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

57     <K_15 extends keyof MathMLElementTagNameMap>(selectors: K_15): NodeListOf<MathMLElementTagNameMap[K_15]>;
                           ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/webdriverio/build/commands/element/getProperty.d.ts:57:79 - error TS2552: Cannot find name 'MathMLElementTagNameMap'. Did you mean 'HTMLElementTagNameMap'?

57     <K_15 extends keyof MathMLElementTagNameMap>(selectors: K_15): NodeListOf<MathMLElementTagNameMap[K_15]>;
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~


Found 9 errors in the same file, starting at: node_modules/webdriverio/build/commands/element/getProperty.d.ts:23
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@PaulKiddle thanks for reporting. We imported a script to get the property from an `HTMLElement` and it seems like using that type caused the TS compiler to inject a whole bunch of unneeded typings that were causing these issue. I pushed a patch with a fix for it.
