### PR TITLE
Support ESM specs with Mocha

### PR DESCRIPTION
**Pull request by diachedelic**
## Proposed changes

Mocha#loadFiles only support CommonJS, so I replaced it with
Mocha#loadFilesAsync which supports both CommonJS and ESM.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by diachedelic** [comment]
Source: https://mochajs.org/api/mocha#loadFilesAsync

**Comment by christian-bromann** [comment]
@diachedelic thanks a lot for the patch. I think you need to adapt the [Mocha mock](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-mocha-framework/tests/__mocks__/mocha.js) to get tests passing.

**Comment by diachedelic** [comment]
Ah yes, done!

**Review by christian-bromann — APPROVED** [review]
👍 thanks!

**Comment by unickq** [comment]
Did it pass all the tests? @christian-bromann 

Looks like after update to 6.4.7 I can't run any test with `npx wdio --spec`.  Is there a way to retrieve wdio logs?

**Comment by diachedelic** [comment]
Running `wdio --spec` using v6.4.7 is working for me - I ran unit tests but I'm not sure if there were any e2e tests I should have run.

**Comment by christian-bromann** [comment]
@unickq it passed all tests and was released with the latest version.

**Comment by unickq** [comment]
weird. I had to downgrade it back to 6.4.0 for all my ts projects. 

Thanks anyway

**Comment by vchuchkalov** [comment]
same. I had to downgrade it back to 6.4.0 for all my ts projects.
6.4.7 passes all tests without passing them.

**Comment by christian-bromann** [comment]
@unickq @vchuchkalov could you provide a minimal reproducible example?

**Comment by vchuchkalov** [comment]
this happens when there is no function implementation or other errors before the test starts
```
[0-0] 2020-09-14T09:17:48.112Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-09-14T09:18:00.188Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-09-14T09:18:00.190Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] 2020-09-14T09:18:05.474Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/User/WebstormProjects/myProject/autotests/test/ui/mainPage/errorDesktop1.ts
 Error:  TypeError: elements.MeetupsListDesktop is not a function
```

**Comment by vchuchkalov** [comment]
my `elements.MeetupsListDesktop` function gets implementation in the before hook.

**Comment by unickq** [comment]
Probably found why it happens.
I have a file with [commands ](https://webdriver.io/docs/customcommands.html) - browserCommands.
Which I load in 

```js
framework: "mocha",
  mochaOpts: {
    ui: "bdd",
    timeout: 90000,
    require: [
      "ts-node/register",
      "tsconfig-paths/register",
      "src/wdio/browserCommands",
    ],
  },
```
Just noticed that it throws warn on 6.4.0 as well.
```
WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): C:\Git\q\download.spec.ts
Error:  Error: Module src/wdio/browserCommands can't get loaded. Are you sure you have installed it?
Note: if you've installed WebdriverIO globally you need to install these external modules globally too!
```
But tests are running even with this warning.

After update to 6.4.7 - I see the same warning, but tests don't start.

So if I remove  "src/wdio/browserCommands" from **mochaOpts** - everything is gonna be fine, but I won't have my commands active.
```
[0-0] RUNNING in chrome - C:\Git\q\download.spec.ts
[0-0] TypeError in "Cards Download Finish option "before all" hook for "Card size - Half""
this.root.$(...).waitUntilClickable is not a function
```

@christian-bromann so is there a correct way to config custom commands for TS?

**Comment by christian-bromann** [comment]
> so is there a correct way to config custom commands for TS?

You can also use the `before` hook in your wdio.conf.js but I feel like this should continue to work given that we initialise the browser instance before we initialise the framework. Would you mind setting up a minimal TS project that reproduces this? I would be happy to look into it.

**Comment by unickq** [comment]
> Would you mind setting up a minimal TS project that reproduces this? I would be happy to look into it.

[example.zip](https://github.com/webdriverio/webdriverio/files/5217501/example.zip)
`wdio.conf.js` line 142

**Comment by diachedelic** [comment]
I can confirm that if a spec fails to load, it is immediately reported as a success (try including some invalid syntax and you'll see what I mean), and I'm not using typescript.

**Comment by alecf** [comment]
I'm seeing some of my tests fail to load starting in 6.4.7 and had to back down to 6.4.0 - could this PR be the cause of #5874 ?

**Comment by diachedelic** [comment]
@alecf could you please post your wdio.log for the failing specs? When my specs failed to load, the error message was printed in there.

**Comment by alecf** [comment]
@diachedelic I'll post it over in #5874
