### ISSUE TITLE
executeHooksWithArgs(...).finally is not a function

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#1477]
## The problem

Today when my CI installed the latest version of webdriverio and its subdeps, my tests failed.  My tests haven't changed and worked with webdriverio 4.1.1.

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 5.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

## Details

I diffed the working and non working deps and got this:

```
Andys-MBP:integration-test andy$ diff working.txt not-working.txt | grep wdio
< ├─┬ wdio-mocha-framework@0.3.4 
> ├─┬ wdio-mocha-framework@0.3.9 
< │ └─┬ wdio-sync@0.5.5 
> │ └─┬ wdio-sync@0.5.10 
Andys-MBP:integration-test andy$ diff working.txt not-working.txt | grep webdriverio
< └─┬ webdriverio@4.1.1 
> └─┬ webdriverio@4.2.1 
```

## Link to Selenium/WebdriverIO logs

https://gist.github.com/jedwards1211/8f480a7741bff8b1d94cda44cbe658fc

## Code To Reproduce Issue [ Good To Have ]

[wdio.conf.js](https://gist.github.com/jedwards1211/eb0eb0d5dd7f0864a8deabd5c76b614a)

(Of course this will not work outside of our private CI environment)

```es6
import {expect} from 'chai'
import Promise from 'bluebird'
import 'core-js'
import 'regenerator-runtime/runtime'

describe('integration test setup', () => {
  it('page loads with correct title', function () {
    browser.url(process.env.APP_URL)
    const title = browser.getTitle()
    expect(title).to.equal('jcore.io')
  })
  
  it('allows user to log in', function() {
    browser.url(process.env.APP_URL)
    // log out just in case it automatically logs in
    browser.executeAsync(done => Meteor.logout(done))
    const passwordInput = browser.element('input[type="password"]')
    passwordInput.waitForExist()
    passwordInput.waitForEnabled()
    const usernameInput = browser.element('input[placeholder="Username"]')
    usernameInput.setValue('admin')
    passwordInput.setValue('password')
    passwordInput.submitForm()
    browser.waitUntil(() => browser.execute(() => Boolean(Meteor.user())), 5000)
  })
})
```

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
@jedwards1211 thanks for posting, will look into it asap

**Comment by christian-bromann** [comment]
I will unpublish new current wdio-mocha-adapter for time being

**Comment by jedwards1211** [comment]
okay, thanks!

**Comment by christian-bromann** [comment]
@jedwards1211 I can't reproduce this. Could you retry without all the imports?

**Comment by christian-bromann** [comment]
Just republish `wdio-mocha-framework@0.3.10` and tried running a simple test like
```js
describe('test', function () {
  it('this', function () {
    browser.url('http://google.com')
    console.log(browser.getTitle());
  })
})
```
and worked just fine with the latest versions:

<details>
├─┬ wdio-mocha-framework@0.3.10
│ ├─┬ babel-runtime@5.8.38
│ │ └── core-js@1.2.7
│ ├─┬ mocha@2.5.3
│ │ ├── commander@2.3.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── diff@1.4.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ glob@3.2.11
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.7.3
│ │ │   └── sigmund@1.0.1
│ │ ├── growl@1.9.2
│ │ ├─┬ jade@0.26.3
│ │ │ ├── commander@0.6.1
│ │ │ └── mkdirp@0.3.0
│ │ ├── supports-color@1.2.0
│ │ └── to-iso-string@0.0.2
│ └─┬ wdio-sync@0.5.10
│   ├── fibers@1.0.13
│   ├─┬ object.assign@4.0.4
│   │ ├─┬ define-properties@1.1.2
│   │ │ └── foreach@2.0.5
│   │ ├── function-bind@1.1.0
│   │ └── object-keys@1.0.11
│   └── promise.prototype.finally@1.0.1
└─┬ webdriverio@4.2.1
  ├─┬ archiver@1.0.0
  │ ├─┬ archiver-utils@1.2.0
  │ │ ├─┬ glob@7.0.5
  │ │ │ └── minimatch@3.0.2
  │ │ ├── graceful-fs@4.1.4
  │ │ ├── lazystream@1.0.0
  │ │ └── normalize-path@2.0.1
  │ ├── async@1.5.2
  │ ├── buffer-crc32@0.2.5
  │ ├─┬ glob@7.0.5
  │ │ ├── fs.realpath@1.0.0
  │ │ └── minimatch@3.0.2
  │ ├── lodash@4.13.1
  │ ├─┬ readable-stream@2.1.4
  │ │ ├── buffer-shims@1.0.0
  │ │ ├── core-util-is@1.0.2
  │ │ ├── isarray@1.0.0
  │ │ ├── process-nextick-args@1.0.7
  │ │ ├── string_decoder@0.10.31
  │ │ └── util-deprecate@1.0.2
  │ ├─┬ tar-stream@1.5.2
  │ │ ├── end-of-stream@1.1.0
  │ │ └── xtend@4.0.1
  │ └─┬ zip-stream@1.0.0
  │   └─┬ compress-commons@1.0.0
  │     ├── crc32-stream@1.0.0
  │     └── node-int64@0.4.0
  ├─┬ css-parse@2.0.0
  │ └─┬ css@2.2.1
  │   ├─┬ source-map@0.1.43
  │   │ └── amdefine@1.0.0
  │   ├─┬ source-map-resolve@0.3.1
  │   │ ├── atob@1.1.3
  │   │ ├── resolve-url@0.2.1
  │   │ └── source-map-url@0.3.0
  │   └── urix@0.1.0
  ├── css-value@0.0.1
  ├── deepmerge@0.2.10
  ├── ejs@2.4.2
  ├─┬ glob@5.0.15
  │ ├─┬ inflight@1.0.5
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@3.0.2
  │ │ └─┬ brace-expansion@1.1.6
  │ │   ├── balanced-match@0.4.2
  │ │   └── concat-map@0.0.1
  │ ├── once@1.3.3
  │ └── path-is-absolute@1.0.0
  ├─┬ inquirer@0.8.5
  │ ├── ansi-regex@1.1.1
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.0.0
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.0.0
  │ │ └── supports-color@2.0.0
  │ ├── cli-width@1.1.1
  │ ├─┬ figures@1.7.0
  │ │ ├── escape-string-regexp@1.0.5
  │ │ └── object-assign@4.1.0
  │ ├── lodash@3.10.1
  │ ├─┬ readline2@0.1.1
  │ │ ├── mute-stream@0.0.4
  │ │ └── strip-ansi@2.0.1
  │ ├── rx@2.5.3
  │ └── through@2.3.8
  ├── json-stringify-safe@5.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ npm-install-package@1.0.2
  │ └── noop2@2.0.0
  ├─┬ optimist@0.6.1
  │ └── wordwrap@0.0.3
  ├── q@1.3.0
  ├─┬ request@2.72.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.4.1
  │ ├─┬ bl@1.1.2
  │ │ └── readable-stream@2.0.6
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├── form-data@1.0.0-rc4
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.13.1
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ └── jsonpointer@2.0.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.0
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.2
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.8.3
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├─┬ dashdash@1.14.0
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.13.3
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├─┬ mime-types@2.1.11
  │ │ └── mime-db@1.23.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.1.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.2
  │ └── tunnel-agent@0.4.3
  ├── rgb2hex@0.1.0
  ├── supports-color@1.3.1
  ├─┬ url@0.10.3
  │ ├── punycode@1.3.2
  │ └── querystring@0.2.0
  ├─┬ validator@4.9.0
  │ └── depd@1.1.0
  ├── wdio-dot-reporter@0.0.4
  └── wgxpath@1.0.0
</details>

**Comment by jedwards1211** [comment]
Ah, `import 'core-js'` is what breaks it.  Is `wdio-mocha-framework` using some `Promise` polyfill that's getting stomped on by `core-js`?  Perhaps it could import from a promise library instead of using a polyfill that touches the global namespace?

**Comment by jedwards1211** [comment]
`.finally` is not a method in the built-in ES2015 promise standard, so I'm guessing webdriver isn't currently compatible with an ES2015 environment.

**Comment by christian-bromann** [comment]
> so I'm guessing webdriver isn't currently compatible with an ES2015 environment

No! I added a polyfill to use finally in my code. Why do you have to import core.js?

**Comment by christian-bromann** [comment]
Closing, I believe the way you use babel is not correct. See http://webdriver.io/guide/getstarted/configuration.html how to use Webdriver.io with Babel.

**Comment by jedwards1211** [comment]
Okay, yes, in `wdio-sync` you are using `https://www.npmjs.com/package/promise.prototype.finally`, which appears to monkeypatch a `finally` method onto whatever `Promise` is in the global namespace.  `core-js` overwrites the `Promise` that's in the global namespace.

This is why monkeypatching is discouraged.  The only reason `core-js` is excused is that it's THE polyfill for providing a standard ES2015 environment.  I think these days most devs only accept monkeypatching if it polyfills next-gen JS standards.  I don't have to use `core-js` right now, but if I want to use certain ES2015 features (and I'm sure I and many devs will), we will have to import `core-js`.  If I can manage to get `core-js` evaluated before `promise.prototype.finally` it will work, but is that possible?

So, would you accept a PR that removes the need to use `promise.prototype.finally`?  If it's not removed I'm almost certain others will start running into this issue.

**Comment by christian-bromann** [comment]
> but is that possible?

Yes! You have to use Mocha's `compiler` or `require` options for that. This way the monkeypatch still works

> would you accept a PR that removes the need to use promise.prototype.finally?

Not for now. I will have to see if more people run into issues with that monkey patch. I think it is fine the way it is especially because I believe it will get into the ES standard eventually.

**Comment by jedwards1211** [comment]
I'm always disappointed when maintainers stick to options that end up biting people and wasting several hours of their day.  You could make developers' lives easier.

**Comment by christian-bromann** [comment]
> that end up biting people and wasting several hours of their day

I am sure that it won't bite anyone using Babel correctly 😉 . It can only break if you overwrite `Promise` within your test spec and that is called monkeypatching and is discouraged :-P

**Comment by jedwards1211** [comment]
Note: the configuration instructions for jasmine advise loading the ES2015 polyfills in userland in a `before` call, which would cause the same problem as I'm having here.

**Comment by jedwards1211** [comment]
So even if people are using Babel correctly with jasmine it will bite them

**Comment by christian-bromann** [comment]
> So even if people are using Babel correctly with jasmine it will bite them

Lemme check that

**Comment by jedwards1211** [comment]
Also, using `compilers: ['js:babel-core/register']` as recommended in the docs doesn't import the polyfill (see https://babeljs.io/docs/usage/require/).  Hence the docs don't really make it clear how to use full ES2015 (compiler and polyfill) with webdriverio

**Comment by huanghaiyang** [comment]
I use `require("babel-polyfill"); `in my test.js.
so I get the same problem.

**Comment by christian-bromann** [comment]
@huanghaiyang as I said it is not the recommended way to use babel-polyfill.

**Comment by jedwards1211** [comment]
@christian-bromann what is the recommended way?  As I mentioned, with Babel 6 at least, nothing in the docs (including `compilers: ['js:babel-core/register']`) actually activates the polyfill.
